"""v0.8.1-K readiness check: Local Mock Data Fixture JSON Artifact Creation Final Authorization Plan (plan-first / final-authorization-plan-only).

Final-authorization-plan verification. Checks that the v0.8.1-K plan document exists and contains
the required sections (1-72), the current-master marker, the v0.8.1-K plan-first /
final-authorization-plan-only markers, the relationship-to-v0.8.1-J / v0.8.1-I / v0.8.1-H markers,
the problem-statement markers, the Local Mock Data Fixture JSON Artifact Creation Final Authorization
Plan definition markers, the final authorization planning / fixture JSON artifact prohibition
boundary markers, the final authorization input / output boundary markers, the exact future explicit
Owner authorization phrase gate markers, the non-authorizing phrase list markers, the final
authorization decision values / request blueprint / decision blueprint markers, the permission-flag
and boolean safety invariant markers, the candidate artifact path / filename / schema version /
top-level shape / records collection / record count / ordering final review markers, the synthetic
local-only / no-real-data final review markers, the required fields / forbidden fields / message
family final review markers, the per-family final review markers (Mock Task / Decision / Result /
Advice Message, Mock Badge Status, Mock Runtime-off Status), the pre-creation safety gate /
creation-only allowed scope / loader / Dashboard / app / queue / Remote Blackboard API / Worker /
OpenClaw / Hermes / Google Sheets / secrets / network boundary markers, the Owner final
authorization / rejection checklist markers, the final authorization record blueprint markers, the
final authorization validation checklist markers, the forbidden fields rejection checklist markers,
the boolean safety invariant checklist markers, the message family final checklist markers, the
disabled runtime list markers, the current safe posture markers, the validation summary markers, the
safety grep summary markers, and the next recommended step (v0.8.1-L) — and that it asserts no
unsafe "implemented / created / added / enabled / activated / connected / called / started / written
/ read / modified / moved / migrated" claim, no artifact-creation / loader / dashboard-change /
execution / dispatch / external-side-effects permission grant, and contains no real secret value.

The document is allowed to contain safe negations and forbidden-field planning tokens (bare field
names such as refresh_token / client_secret / private_key / spreadsheet_id, listed in the Forbidden
fields rejection checklist). Safe negations that literally embed a forbidden substring are scrubbed
before the forbidden scan; the secret patterns only match value-bearing forms (name = "value"), so
bare planning tokens are not mis-flagged.

This script only reads the plan document. It does NOT read .env, credentials, tokens, or secrets,
makes no network call, imports no app logic (no app.main, no QueueStore), adds no API route /
router / Dashboard route / template / static / database client / migration, creates no production /
shared DB, creates no fixture JSON, no .json artifact, no mock data file, no seed data file, no
fixture directory, no preview data loader, builds no fixture loader runtime, no Dashboard preview
display runtime, reads no real queue DB, writes no queue, sends no POST, starts no Worker, connects
no OpenClaw, activates no Hermes, opens no shared write, and reads/writes no Google Sheets.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
PASS = []
FAIL = []

DOC_PATH = (
    ROOT
    / "docs"
    / "HERMES_OPENCLAW_LOCAL_MOCK_DATA_FIXTURE_JSON_ARTIFACT_CREATION_FINAL_AUTHORIZATION_PLAN_V0_8_1_K.md"
)


def ok(label):
    PASS.append(label)
    print(f"  ok : {label}")


def xx(label):
    FAIL.append(label)
    print(f"  XX : {label}")


# ---------------------------------------------------------------------------
# [1] plan 文件存在
# ---------------------------------------------------------------------------
print("[1] plan 文件存在")
ok("v0.8.1-K plan doc 存在") if DOC_PATH.exists() else xx("v0.8.1-K plan doc 存在")
if not DOC_PATH.exists():
    print("\nXX plan doc 不存在，無法繼續")
    sys.exit(1)

doc = DOC_PATH.read_text(encoding="utf-8")

# ---------------------------------------------------------------------------
# [2] 必須包含的章節（1-72）
# ---------------------------------------------------------------------------
print("[2] 必須包含的章節")
REQUIRED_SECTIONS = [
    "1. Purpose",
    "2. Current master",
    "3. Scope",
    "4. Relationship to v0.8.1-J Local Mock Data Fixture JSON Artifact Creation Authorization Review",
    "5. Relationship to v0.8.1-I Local Mock Data Fixture JSON Artifact Creation Plan",
    "6. Relationship to v0.8.1-H Local Mock Data Fixture JSON Creation Authorization Plan",
    "7. Problem statement",
    "8. Local Mock Data Fixture JSON Artifact Creation Final Authorization Plan definition",
    "9. Final authorization planning boundary",
    "10. Fixture JSON artifact prohibition boundary",
    "11. Final authorization input boundary",
    "12. Final authorization output boundary",
    "13. Explicit Owner authorization phrase gate",
    "14. Non-authorizing phrase list",
    "15. Final authorization decision values",
    "16. Final authorization request blueprint",
    "17. Final authorization decision blueprint",
    "18. Pre-creation safety gate",
    "19. Creation-only allowed scope",
    "20. Loader prohibition boundary",
    "21. Dashboard prohibition boundary",
    "22. App / runtime prohibition boundary",
    "23. Queue and real data prohibition boundary",
    "24. Remote Blackboard API relationship",
    "25. Worker / OpenClaw / Hermes separation boundary",
    "26. Google Sheets prohibition boundary",
    "27. Secrets / privacy / memory boundary",
    "28. Network / webhook / connector boundary",
    "29. Candidate artifact path final review",
    "30. Candidate artifact filename final review",
    "31. Candidate schema version final review",
    "32. Candidate top-level shape final review",
    "33. Candidate records collection final review",
    "34. Candidate record count final review",
    "35. Candidate record ordering final review",
    "36. Synthetic local-only final review",
    "37. No-real-data final review",
    "38. Required fields final review",
    "39. Forbidden fields final review",
    "40. Boolean safety invariant final review",
    "41. Message family final review",
    "42. Mock Task Message final review",
    "43. Mock Decision Message final review",
    "44. Mock Result Message final review",
    "45. Mock Advice Message final review",
    "46. Mock Badge Status final review",
    "47. Mock Runtime-off Status final review",
    "48. Display copy final review",
    "49. Safety notes final review",
    "50. Next owner action final review",
    "51. Audit notes final review",
    "52. Rollback notes final review",
    "53. Future artifact creation command boundary",
    "54. Future artifact validation boundary",
    "55. Future artifact rollback boundary",
    "56. Future read-only loader boundary",
    "57. Future Dashboard preview boundary",
    "58. Failure / rollback / audit boundary",
    "59. Owner final authorization checklist",
    "60. Owner final rejection checklist",
    "61. Final authorization record blueprint",
    "62. Final authorization validation checklist",
    "63. Forbidden fields rejection checklist",
    "64. Boolean safety invariant checklist",
    "65. Message family final checklist",
    "66. Disabled runtime list",
    "67. Current safe system posture",
    "68. Validation summary",
    "69. Safety grep summary",
    "70. Non-goals",
    "71. Acceptance criteria",
    "72. Next recommended step",
]
for section in REQUIRED_SECTIONS:
    ok(f"doc 含章節「{section}」") if section in doc else xx(f"doc 含章節「{section}」")

# ---------------------------------------------------------------------------
# [3] 必須包含的 markers
# ---------------------------------------------------------------------------
print("[3] 必須包含的 markers")
REQUIRED = [
    # version
    "v0.8.1-K",
    "Local Mock Data Fixture JSON Artifact Creation Final Authorization Plan",
    # current master
    "HEAD = origin/master = 6d5f314110e52de34ae7e1e8029573cfb8b52ef7",
    "docs: plan local mock data fixture json artifact creation authorization review",
    # v0.8.1-K plan-first / final-authorization-plan-only markers
    "v0.8.1-K Local Mock Data Fixture JSON Artifact Creation Final Authorization Plan is plan-first.",
    "v0.8.1-K Local Mock Data Fixture JSON Artifact Creation Final Authorization Plan is final-authorization-plan-only.",
    "v0.8.1-K does not create fixture JSON.",
    "v0.8.1-K does not create .json artifact.",
    "v0.8.1-K does not create mock data file.",
    "v0.8.1-K does not create seed data file.",
    "v0.8.1-K does not create fixture directory.",
    "v0.8.1-K does not create preview data loader.",
    "v0.8.1-K does not implement fixture loader runtime.",
    "v0.8.1-K does not implement Dashboard preview display runtime.",
    "v0.8.1-K does not implement local mock data preview runtime.",
    "v0.8.1-K does not create Dashboard route.",
    "v0.8.1-K does not create Dashboard endpoint.",
    "v0.8.1-K does not create Dashboard template.",
    "v0.8.1-K does not create Dashboard static asset.",
    "v0.8.1-K does not modify app.",
    "v0.8.1-K does not modify templates.",
    "v0.8.1-K does not modify static.",
    "v0.8.1-K does not read real queue DB.",
    "v0.8.1-K does not write queue data.",
    "v0.8.1-K does not send POST.",
    "v0.8.1-K does not start Worker.",
    "v0.8.1-K does not connect OpenClaw.",
    "v0.8.1-K does not activate Hermes.",
    "v0.8.1-K does not connect Hermes.",
    "v0.8.1-K does not read Google Sheets.",
    "v0.8.1-K does not write Google Sheets.",
    "v0.8.1-K does not read secrets.",
    "v0.8.1-K does not create .env.",
    "v0.8.1-K does not create webhook.",
    "v0.8.1-K does not create connector.",
    "v0.8.1-K does not create Remote Blackboard API runtime.",
    "v0.8.1-K does not create production DB.",
    "v0.8.1-K does not create shared DB.",
    "v0.8.1-K does not open shared write.",
    # relationship to v0.8.1-J
    "v0.8.1-J Local Mock Data Fixture JSON Artifact Creation Authorization Review is complete.",
    "v0.8.1-K starts the Local Mock Data Fixture JSON Artifact Creation Final Authorization Plan step.",
    "v0.8.1-K builds on Local Mock Data Fixture JSON Artifact Creation Authorization Review.",
    "v0.8.1-K plans the final authorization gate before any fixture JSON is created.",
    "v0.8.1-K preserves Owner final approval authority.",
    "v0.8.1-K preserves decision and dispatch separation.",
    "v0.8.1-K preserves audit trail.",
    "v0.8.1-K preserves dispatch-disabled boundary.",
    "v0.8.1-K preserves local mock data preview boundary.",
    "v0.8.1-K preserves the fixture contract boundary.",
    "v0.8.1-K preserves the fixture draft boundary.",
    "v0.8.1-K preserves the fixture JSON approval boundary.",
    "v0.8.1-K preserves the fixture JSON creation boundary.",
    "v0.8.1-K preserves the candidate artifact planning boundary.",
    "v0.8.1-K preserves the artifact owner approval boundary.",
    "v0.8.1-K preserves the creation authorization boundary.",
    "v0.8.1-K preserves the artifact creation plan boundary.",
    "v0.8.1-K preserves the authorization review boundary.",
    "v0.8.1-K preserves read-only Dashboard display boundary.",
    "v0.8.1-K does not change any v0.8.1-J boundary.",
    "v0.8.1-K does not change any v0.8.1-I boundary.",
    "v0.8.1-K does not change any v0.8.1-H boundary.",
    "v0.8.1-K does not change any v0.8.1-G boundary.",
    "v0.8.1-K does not change any v0.8.1-F boundary.",
    "v0.8.1-K does not change any v0.8.1-E boundary.",
    "v0.8.1-K does not change any v0.8.1-D boundary.",
    "v0.8.1-K does not change any v0.8.1-C boundary.",
    "v0.8.1-K does not change any v0.8.1-B boundary.",
    "v0.8.1-K does not change any v0.8.1-A boundary.",
    "v0.8.1-K does not change any v0.8.0-G boundary.",
    "v0.8.1-K does not change any v0.8.0-F boundary.",
    # relationship to v0.8.1-I
    "v0.8.1-I defined the artifact blueprint.",
    "v0.8.1-K does not modify the artifact blueprint.",
    "v0.8.1-K does not create the artifact blueprint as JSON.",
    "v0.8.1-K only plans the final authorization gate for a future artifact creation step.",
    # relationship to v0.8.1-H
    "v0.8.1-H defined the future explicit Owner authorization phrase.",
    "v0.8.1-K does not issue the explicit Owner authorization phrase.",
    "v0.8.1-K does not satisfy the explicit Owner authorization phrase.",
    "v0.8.1-K does not convert final authorization planning into artifact creation permission.",
    "v0.8.1-K does not convert final authorization planning into execution permission.",
    "v0.8.1-K does not convert final authorization planning into dispatch permission.",
    # definition
    "Local Mock Data Fixture JSON Artifact Creation Final Authorization Plan means the planning-only",
    "Local Mock Data Fixture JSON Artifact Creation Final Authorization Plan is a planning artifact in v0.8.1-K.",
    "Local Mock Data Fixture JSON Artifact Creation Final Authorization Plan is not runtime code.",
    "Local Mock Data Fixture JSON Artifact Creation Final Authorization Plan is not a fixture JSON file.",
    "Local Mock Data Fixture JSON Artifact Creation Final Authorization Plan is not a mock data file.",
    "Local Mock Data Fixture JSON Artifact Creation Final Authorization Plan is not a preview data loader.",
    "Local Mock Data Fixture JSON Artifact Creation Final Authorization Plan requires the exact explicit Owner authorization phrase before artifact creation.",
    # safety principles
    "Approval is not execution.",
    "Approval readiness is not execution permission.",
    "Owner approval is not dispatch permission.",
    "Creation authorization is not execution permission.",
    "Final authorization planning is not artifact creation.",
    "Final authorization planning is not fixture JSON creation.",
    "Final authorization planning is not mock data file creation.",
    "Final authorization planning is not execution permission.",
    "Final authorization planning is not Worker dispatch.",
    "Final authorization planning is not OpenClaw call.",
    "Final authorization planning is not Hermes action.",
    "Final authorization planning must not read real queue DB.",
    "Final authorization planning must not send POST.",
    "Final authorization planning must not create fixture JSON.",
    "Final authorization planning must not create preview data loader.",
    "Decision and dispatch remain separate.",
    "Dashboard preview display is read-only.",
    # final authorization planning boundary
    "Final authorization planning boundary is planning only.",
    "Final authorization planning is expressed as text and pseudo-field descriptions only.",
    "No final authorization planning runtime is implemented in v0.8.1-K.",
    "Final authorization planning does not grant artifact creation permission.",
    # fixture JSON artifact prohibition boundary
    "Fixture JSON artifact prohibition boundary is planning only.",
    "No fixture JSON is created in v0.8.1-K.",
    "No .json artifact is created in v0.8.1-K.",
    "No JSON object is created in v0.8.1-K.",
    "Fixture JSON artifact creation requires separate Owner authorization.",
    # final authorization input boundary
    "Final authorization input boundary is planning only.",
    "Final authorization inputs are the v0.8.1-J authorization review, the v0.8.1-I artifact blueprint, and the v0.8.1-H authorization relationship.",
    "Final authorization inputs are read as planning text only.",
    "Final authorization inputs do not include real queue DB.",
    "Final authorization inputs do not include Google Sheets.",
    "Final authorization inputs do not include secrets.",
    "No final authorization input runtime is implemented in v0.8.1-K.",
    # final authorization output boundary
    "Final authorization output boundary is planning only.",
    "Final authorization output is a planning-only final authorization record blueprint.",
    "Final authorization output is not a fixture JSON file.",
    "Final authorization output is not a mock data file.",
    "Final authorization output is not a loader.",
    "Final authorization output does not grant artifact creation permission.",
    "Final authorization output does not grant execution permission.",
    "Final authorization output does not grant dispatch permission.",
    "No final authorization output runtime is implemented in v0.8.1-K.",
    # explicit Owner authorization phrase gate (exact phrase)
    "Future explicit Owner authorization phrase:",
    "批准建立 v0.8.1 local mock fixture JSON artifact，僅建立 synthetic local-only fixture JSON file，不建立 loader，不改 Dashboard，不讀 real queue DB，不 POST，不啟 Worker/OpenClaw/Hermes/Google Sheets。",
    "The future explicit Owner authorization phrase is planning text in v0.8.1-K.",
    "The future explicit Owner authorization phrase is not issued in v0.8.1-K.",
    "The future explicit Owner authorization phrase is not satisfied in v0.8.1-K.",
    "The future explicit Owner authorization phrase must be separately issued by Owner in a future step before any fixture JSON artifact may be created.",
    "No fixture JSON may be created from v0.8.1-K.",
    # non-authorizing phrase list
    "Non-authorizing phrase: approve readiness.",
    "Non-authorizing phrase: approve plan.",
    "Non-authorizing phrase: approve Owner review.",
    "Non-authorizing phrase: approve authorization review.",
    "Non-authorizing phrase: approve final authorization plan.",
    "Non-authorizing phrase: looks good.",
    "Non-authorizing phrase: proceed to next step.",
    "Non-authorizing phrase: continue.",
    "Non-authorizing phrase: commit this plan.",
    "Non-authorizing phrase: push this plan.",
    "Non-authorizing phrase: start v0.8.1-K.",
    "Non-authorizing phrase: start v0.8.1-L.",
    "None of these phrases authorizes fixture JSON creation.",
    # final authorization decision values
    "Final authorization decision value: authorize_synthetic_fixture_json_creation_only.",
    "Final authorization decision value: reject_synthetic_fixture_json_creation.",
    "Final authorization decision value: request_revision.",
    "Final authorization decision value: defer_decision.",
    "Final authorization decision values are planning only.",
    "No final authorization decision runtime is implemented in v0.8.1-K.",
    # final authorization request blueprint
    "Final authorization request blueprint is planning only.",
    "Final authorization request may include final_authorization_request_id.",
    "Final authorization request may include reviewed_plan_version.",
    "Final authorization request may include reviewed_authorization_review_version.",
    "Final authorization request may include candidate_fixture_path.",
    "Final authorization request may include candidate_schema_version.",
    "Final authorization request may include explicit_authorization_phrase_required.",
    "Final authorization request may include creation_scope.",
    "Final authorization request may include synthetic_local_only_confirmation.",
    "Final authorization request may include no_real_data_confirmation.",
    "Final authorization request may include required_fields_confirmation.",
    "Final authorization request may include forbidden_fields_absent_confirmation.",
    "Final authorization request may include boolean_invariants_confirmation.",
    "Final authorization request may include no_loader_confirmation.",
    "Final authorization request may include no_dashboard_change_confirmation.",
    "Final authorization request may include no_real_queue_db_confirmation.",
    "Final authorization request may include no_post_confirmation.",
    "Final authorization request may include no_worker_openclaw_hermes_confirmation.",
    "Final authorization request may include no_google_sheets_confirmation.",
    "Final authorization request may include no_secrets_confirmation.",
    "Final authorization request may include rollback_notes_required.",
    "Final authorization request may include audit_notes_required.",
    "No final authorization request is created in v0.8.1-K.",
    # final authorization decision blueprint
    "Final authorization decision blueprint is planning only.",
    "Final authorization decision may include final_authorization_decision_id.",
    "Final authorization decision may include final_authorization_request_id.",
    "Final authorization decision may include owner_decision.",
    "Final authorization decision may include authorized_scope.",
    "Final authorization decision may include rejected_reason.",
    "Final authorization decision may include authorization_timestamp.",
    "Final authorization decision may include authorization_notes.",
    "Final authorization decision may include rollback_notes.",
    "Final authorization decision may include artifact_creation_permission.",
    "Final authorization decision may include loader_permission.",
    "Final authorization decision may include dashboard_change_permission.",
    "Final authorization decision may include execution_permission.",
    "Final authorization decision may include dispatch_permission.",
    "Final authorization decision may include external_side_effects_permission.",
    "No final authorization decision is created in v0.8.1-K.",
    # pre-creation safety gate
    "Pre-creation safety gate is planning only.",
    "Pre-creation safety gate requires the exact explicit Owner authorization phrase.",
    "Pre-creation safety gate blocks creation if any confirmation is missing.",
    "No pre-creation safety gate runtime is implemented in v0.8.1-K.",
    # creation-only allowed scope
    "Creation-only allowed scope is planning only.",
    "Creation-only allowed scope: create only the synthetic local-only fixture JSON file.",
    "Creation-only allowed scope excludes any loader.",
    "Creation-only allowed scope excludes any Dashboard change.",
    "Creation-only allowed scope excludes any runtime.",
    "No creation-only scope runtime is implemented in v0.8.1-K.",
    # permission flags remain false
    "artifact_creation_permission = false",
    "loader_permission = false",
    "dashboard_change_permission = false",
    "execution_permission = false",
    "dispatch_permission = false",
    "external_side_effects_permission = false",
    "In v0.8.1-K artifact_creation_permission remains false.",
    "In v0.8.1-K loader_permission remains false.",
    "In v0.8.1-K dashboard_change_permission remains false.",
    "In v0.8.1-K execution_permission remains false.",
    "In v0.8.1-K dispatch_permission remains false.",
    "In v0.8.1-K external_side_effects_permission remains false.",
    "Final authorization planning does not grant loader permission.",
    "Final authorization planning does not grant Dashboard change permission.",
    "Final authorization planning does not grant execution permission.",
    "Final authorization planning does not grant dispatch permission.",
    "Final authorization planning does not grant external side effects permission.",
    # boolean safety invariants
    "is_mock = true",
    "dispatch_enabled = false",
    "worker_running = false",
    "openclaw_connected = false",
    "hermes_connected = false",
    "google_sheets_enabled = false",
    "external_side_effects = false",
    "approval_is_execution = false",
    "approval_readiness_is_execution = false",
    "No boolean safety invariant runtime is implemented in v0.8.1-K.",
    # candidate artifact path final review
    "Candidate fixture JSON path: fixtures/local_mock_data/hermes_openclaw_local_mock_messages_v0_8_1.json",
    "Candidate fixture JSON path final review is planning only.",
    "Candidate fixture JSON path is not created in v0.8.1-K.",
    "Candidate fixture directory is not created in v0.8.1-K.",
    "Candidate fixture JSON file is not created in v0.8.1-K.",
    "Candidate artifact path is inherited from v0.8.1-I planning.",
    # candidate artifact filename final review
    "Candidate fixture JSON filename: hermes_openclaw_local_mock_messages_v0_8_1.json",
    "Candidate fixture JSON filename final review is planning only.",
    "Candidate fixture JSON filename is not created in v0.8.1-K.",
    # candidate schema version final review
    "Candidate fixture JSON schema_version: v0.8.1-local-mock-1.",
    "Candidate schema version final review is planning only.",
    "Candidate schema version is not implemented in v0.8.1-K.",
    "No schema migration is performed in v0.8.1-K.",
    # candidate top-level shape final review
    "Candidate top-level shape final review is planning only.",
    "Candidate top-level shape may include schema_version.",
    "Candidate top-level shape may include fixture_id.",
    "Candidate top-level shape may include is_mock.",
    "Candidate top-level shape may include created_for.",
    "Candidate top-level shape may include records.",
    # candidate records collection final review
    "Candidate records collection final review is planning only.",
    "Candidate records collection may include six synthetic local-only records.",
    "Candidate records collection must not include real queue data.",
    "Candidate records collection must not include real user data.",
    "Candidate records collection must not include secrets.",
    "Candidate records collection must not include endpoints.",
    "No records collection is created in v0.8.1-K.",
    # candidate record count final review
    "Candidate record count final review: six records.",
    "Candidate record count final review is planning only.",
    "No record is created in v0.8.1-K.",
    # candidate record ordering final review
    "Candidate record ordering final review: Mock Task Message first.",
    "Candidate record ordering final review: Mock Decision Message second.",
    "Candidate record ordering final review: Mock Result Message third.",
    "Candidate record ordering final review: Mock Advice Message fourth.",
    "Candidate record ordering final review: Mock Badge Status fifth.",
    "Candidate record ordering final review: Mock Runtime-off Status sixth.",
    "Candidate record ordering final review is planning only.",
    # synthetic local-only final review
    "Synthetic local-only final review: all candidate values must be synthetic.",
    "Synthetic local-only final review: all candidate values must be local-only.",
    "Synthetic local-only final review: no value may be copied from real queue DB.",
    "Synthetic local-only final review: no value may be copied from Google Sheets.",
    "Synthetic local-only final review: no value may be copied from secrets.",
    "Synthetic local-only final review: no value may be copied from production logs.",
    "Synthetic local-only final review: no value may be copied from private user data.",
    "No real data is used in v0.8.1-K.",
    # no-real-data final review
    "No-real-data final review: future artifact must contain no real queue IDs.",
    "No-real-data final review: future artifact must contain no real task IDs.",
    "No-real-data final review: future artifact must contain no real user data.",
    "No-real-data final review: future artifact must contain no spreadsheet IDs.",
    "No-real-data final review: future artifact must contain no tokens.",
    "No-real-data final review: future artifact must contain no secrets.",
    "No-real-data final review: future artifact must contain no endpoints.",
    # required fields
    "Required fields final review is planning only.",
    "fixture_id",
    "schema_version",
    "is_mock",
    "message_family",
    "message_id",
    "preview_id",
    "created_for",
    "display_title",
    "display_summary",
    "safety_notes",
    "next_owner_action",
    "audit_notes",
    "rollback_notes",
    "No required field is implemented in v0.8.1-K.",
    # forbidden fields
    "Forbidden fields final review is planning only.",
    "real_queue_id",
    "real_task_id",
    "real_user_secret",
    "spreadsheet_id",
    "refresh_token",
    "client_secret",
    "private_key",
    "webhook_url",
    "openclaw_endpoint",
    "hermes_endpoint",
    "production_db_url",
    "remote_blackboard_api_url",
    "No forbidden field value is included in v0.8.1-K.",
    # message families
    "Mock Task Message",
    "Mock Decision Message",
    "Mock Result Message",
    "Mock Advice Message",
    "Mock Badge Status",
    "Mock Runtime-off Status",
    # per-family final review
    "Mock Task Message final review is planning only.",
    "No Mock Task Message record is created in v0.8.1-K.",
    "Mock Decision Message final review is planning only.",
    "No Mock Decision Message record is created in v0.8.1-K.",
    "Mock Result Message final review is planning only.",
    "No Mock Result Message record is created in v0.8.1-K.",
    "Mock Advice Message final review is planning only.",
    "No Mock Advice Message record is created in v0.8.1-K.",
    "Mock Badge Status final review is planning only.",
    "No Mock Badge Status record is created in v0.8.1-K.",
    "Mock Runtime-off Status final review is planning only.",
    "No Mock Runtime-off Status record is created in v0.8.1-K.",
    # future artifact creation command boundary
    "Future artifact creation command boundary is planning only.",
    "Future artifact creation command must be separately Owner-authorized.",
    "Future artifact creation command must create only the synthetic local-only fixture JSON file.",
    "Future artifact creation command must not create a loader.",
    "Future artifact creation command must not modify Dashboard route/template/static.",
    "Future artifact creation command must not read real queue DB.",
    "Future artifact creation command must not send POST.",
    "Future artifact creation command must not start Worker.",
    "Future artifact creation command must not call OpenClaw.",
    "Future artifact creation command must not activate Hermes.",
    "Future artifact creation command must not read or write Google Sheets.",
    "No artifact creation command runtime is implemented in v0.8.1-K.",
    # future artifact validation boundary
    "Future artifact validation boundary is planning only.",
    "Future artifact must validate as synthetic local-only before any use.",
    "Future artifact must contain only approved message families.",
    "Future artifact must contain only approved required fields.",
    "Future artifact must contain no forbidden fields.",
    "Future artifact must satisfy boolean safety invariants.",
    "No artifact validation runtime is implemented in v0.8.1-K.",
    # future artifact rollback boundary
    "Future artifact rollback boundary is planning only.",
    "Future artifact must be removable by deleting only the approved local fixture JSON file.",
    "Future artifact rollback must not require database migration.",
    "Future artifact rollback must not require real queue DB write.",
    "Future artifact rollback must not require POST.",
    "No artifact rollback runtime is implemented in v0.8.1-K.",
    # future read-only loader boundary
    "A future read-only loader may read the approved fixture once it exists.",
    "Future read-only loader is display-only.",
    "Future read-only loader is not execution permission.",
    "Future read-only loader must not write the fixture.",
    "Future read-only loader must not read real queue DB.",
    "Future read-only loader must not send POST.",
    "No read-only loader runtime is implemented in v0.8.1-K.",
    "No preview data loader is implemented in v0.8.1-K.",
    # future Dashboard preview boundary
    "Dashboard may eventually display the approved local mock data fixture once created.",
    "Future Dashboard preview is display-only.",
    "No Dashboard fixture preview runtime is implemented in v0.8.1-K.",
    # Dashboard prohibition boundary
    "Dashboard prohibition boundary is planning only.",
    "No Dashboard route is created in v0.8.1-K.",
    "No Dashboard endpoint is created in v0.8.1-K.",
    "No Dashboard template is created in v0.8.1-K.",
    "No Dashboard static asset is created in v0.8.1-K.",
    "No app route is modified in v0.8.1-K.",
    "No template file is modified in v0.8.1-K.",
    "No static file is modified in v0.8.1-K.",
    # app / runtime prohibition boundary
    "App / runtime prohibition boundary is planning only.",
    "No app module is modified in v0.8.1-K.",
    "No app.main import is performed in v0.8.1-K.",
    "No QueueStore import is performed in v0.8.1-K.",
    "No runtime host is created in v0.8.1-K.",
    "No daemon is created in v0.8.1-K.",
    "No systemd service is created in v0.8.1-K.",
    "No Docker deployment is created in v0.8.1-K.",
    "No fixture loader runtime is created in v0.8.1-K.",
    # queue and real data prohibition boundary
    "No source-of-truth switch is performed.",
    "No queue DB change.",
    "No local queue data change.",
    "No Replit queue data change.",
    "No real queue DB read.",
    "No queue migration is performed.",
    "No queue synchronization is performed.",
    "No queue backfill is performed.",
    "No queue merge is performed.",
    "No conflict resolver is implemented.",
    "No shared write is enabled.",
    # Remote Blackboard API relationship
    "Remote Blackboard API remains planning only.",
    "Remote Blackboard API runtime is not implemented in v0.8.1-K.",
    "Remote Blackboard API read is not enabled in v0.8.1-K.",
    "Remote Blackboard API write is not enabled in v0.8.1-K.",
    "Remote Blackboard API is not required for final authorization planning.",
    # separation
    "Worker remains OFF.",
    "OpenClaw remains Not Connected.",
    "Hermes remains Not Connected.",
    "Worker is dispatch runtime.",
    "OpenClaw is execution / gateway / tools layer.",
    "Hermes is strategy / proxy / memory layer.",
    "Worker must not run from plan-only final authorization planning.",
    "OpenClaw must not execute from plan-only final authorization planning.",
    "Hermes must not act from plan-only final authorization planning.",
    # Google Sheets prohibition boundary
    "Google Sheets remains Disabled.",
    "No Google Sheets access is required.",
    "No Google Sheets write is performed.",
    "No Google Sheets live write is enabled.",
    # secrets / privacy / memory boundary
    "No secrets are read.",
    "No secrets are copied.",
    "No secrets are created.",
    "No .env file is created.",
    "No credentials are moved.",
    "No production secrets are copied.",
    "No Hermes memory store is created.",
    "No Hermes learning runtime is created.",
    "No private conversation log is created.",
    "No all-conversation logging is enabled.",
    # network / webhook / connector boundary
    "No webhook is created.",
    "No webhook receiver is created.",
    "No connector is created.",
    "No external network call is added.",
    "No inbound listener is added.",
    "No outbound integration is added.",
    "No port exposure is configured.",
    "No POST is sent.",
    "No live queue write validation is performed.",
    # failure / rollback / audit boundary
    "Failure / rollback / audit boundary is planning only.",
    "On any doubt, stop and ask Owner.",
    "Rollback of v0.8.1-K is deleting only the two planning files.",
    "Audit trail is preserved.",
    # Owner final authorization checklist
    "Owner final authorization checklist: v0.8.1-J authorization review is complete.",
    "Owner final authorization checklist: v0.8.1-I artifact blueprint is reviewed.",
    "Owner final authorization checklist: v0.8.1-H explicit Owner authorization phrase relationship is reviewed.",
    "Owner final authorization checklist: exact explicit Owner authorization phrase is required.",
    "Owner final authorization checklist: candidate artifact path is reviewed.",
    "Owner final authorization checklist: candidate filename is reviewed.",
    "Owner final authorization checklist: candidate schema_version is reviewed.",
    "Owner final authorization checklist: candidate top-level shape is reviewed.",
    "Owner final authorization checklist: candidate records collection is reviewed.",
    "Owner final authorization checklist: candidate record count is reviewed.",
    "Owner final authorization checklist: candidate record ordering is reviewed.",
    "Owner final authorization checklist: synthetic local-only readiness is reviewed.",
    "Owner final authorization checklist: no-real-data readiness is reviewed.",
    "Owner final authorization checklist: required fields are reviewed.",
    "Owner final authorization checklist: forbidden fields are reviewed.",
    "Owner final authorization checklist: boolean safety invariants are reviewed.",
    "Owner final authorization checklist: message families are reviewed.",
    "Owner final authorization checklist: per-record final reviews are reviewed.",
    "Owner final authorization checklist: no loader is authorized.",
    "Owner final authorization checklist: no Dashboard change is authorized.",
    "Owner final authorization checklist: no real queue DB read is required.",
    "Owner final authorization checklist: no POST is required.",
    "Owner final authorization checklist: no Worker/OpenClaw/Hermes action is required.",
    "Owner final authorization checklist: no Google Sheets access is required.",
    "Owner final authorization checklist: no secrets access is required.",
    "Owner final authorization checklist: final authorization planning does not grant artifact creation permission.",
    # Owner final rejection checklist
    "Owner final rejection checklist: reject final authorization if explicit Owner authorization phrase is missing.",
    "Owner final rejection checklist: reject final authorization if forbidden fields are present.",
    "Owner final rejection checklist: reject final authorization if boolean safety invariants are unsafe.",
    "Owner final rejection checklist: reject final authorization if loader permission is requested.",
    "Owner final rejection checklist: reject final authorization if Dashboard change permission is requested.",
    "Owner final rejection checklist: reject final authorization if execution permission is requested.",
    "Owner final rejection checklist: reject final authorization if dispatch permission is requested.",
    "Owner final rejection checklist: reject final authorization if external side effects are requested.",
    "Owner final rejection checklist: reject final authorization if real queue DB read is required.",
    "Owner final rejection checklist: reject final authorization if POST is required.",
    "Owner final rejection checklist: reject final authorization if Worker/OpenClaw/Hermes action is required.",
    "Owner final rejection checklist: reject final authorization if Google Sheets access is required.",
    "Owner final rejection checklist: reject final authorization if secrets access is required.",
    # final authorization record blueprint
    "Final authorization record blueprint is planning only.",
    "No final authorization record is created in v0.8.1-K.",
    # final authorization validation checklist
    "Validation checklist: final authorization plan must remain synthetic local-only.",
    "Validation checklist: final authorization plan must contain no fixture JSON.",
    "Validation checklist: final authorization plan must contain no JSON object.",
    "Validation checklist: final authorization plan must satisfy boolean safety invariants.",
    "Validation checklist: final authorization plan must keep artifact_creation_permission = false.",
    "Validation checklist: final authorization plan must keep loader_permission = false.",
    "Validation checklist: final authorization plan must keep dashboard_change_permission = false.",
    "Validation checklist: final authorization plan must not enable dispatch.",
    "Validation checklist: final authorization plan must not enable Worker.",
    "Validation checklist: final authorization plan must not connect OpenClaw.",
    "Validation checklist: final authorization plan must not activate Hermes.",
    "Validation checklist: final authorization plan must not enable Google Sheets.",
    "Validation checklist: final authorization plan must not read real queue DB.",
    "Validation checklist: final authorization plan must not send POST.",
    "Validation checklist: final authorization plan must not read secrets.",
    # forbidden field rejection checklist
    "Forbidden field rejection checklist: reject if real_queue_id appears as a field.",
    "Forbidden field rejection checklist: reject if real_task_id appears as a field.",
    "Forbidden field rejection checklist: reject if real_user_secret appears as a field.",
    "Forbidden field rejection checklist: reject if spreadsheet_id appears as a field.",
    "Forbidden field rejection checklist: reject if refresh_token appears as a field.",
    "Forbidden field rejection checklist: reject if client_secret appears as a field.",
    "Forbidden field rejection checklist: reject if private_key appears as a field.",
    "Forbidden field rejection checklist: reject if webhook_url appears as a field.",
    "Forbidden field rejection checklist: reject if openclaw_endpoint appears as a field.",
    "Forbidden field rejection checklist: reject if hermes_endpoint appears as a field.",
    "Forbidden field rejection checklist: reject if production_db_url appears as a field.",
    "Forbidden field rejection checklist: reject if remote_blackboard_api_url appears as a field.",
    # boolean safety invariant checklist
    "Boolean safety invariant checklist is planning only.",
    "Boolean safety invariant checklist: is_mock = true.",
    "Boolean safety invariant checklist: artifact_creation_permission = false.",
    "Boolean safety invariant checklist: loader_permission = false.",
    "Boolean safety invariant checklist: dashboard_change_permission = false.",
    "Boolean safety invariant checklist: execution_permission = false.",
    "Boolean safety invariant checklist: dispatch_permission = false.",
    "Boolean safety invariant checklist: external_side_effects_permission = false.",
    # message family final checklist
    "Message family final checklist is planning only.",
    "Message family final checklist: Mock Task Message final review is reviewed.",
    "Message family final checklist: Mock Decision Message final review is reviewed.",
    "Message family final checklist: Mock Result Message final review is reviewed.",
    "Message family final checklist: Mock Advice Message final review is reviewed.",
    "Message family final checklist: Mock Badge Status final review is reviewed.",
    "Message family final checklist: Mock Runtime-off Status final review is reviewed.",
    "No message family record is created in v0.8.1-K.",
    # disabled runtime list
    "Final authorization planning runtime is disabled.",
    "Final authorization decision runtime is disabled.",
    "Artifact creation command runtime is disabled.",
    "Fixture loader runtime is disabled.",
    "Preview data loader runtime is disabled.",
    "Local mock data preview runtime is disabled.",
    "Dashboard fixture preview runtime is disabled.",
    "Blackboard Loop runtime is disabled.",
    "Dashboard badge display runtime is disabled.",
    "Decision audit display runtime is disabled.",
    "Owner review checklist runtime is disabled.",
    "Dashboard preview display runtime is disabled.",
    "Dispatch gate is disabled.",
    "Worker runtime is disabled.",
    "OpenClaw runtime is disabled.",
    "Hermes runtime is disabled.",
    "Remote Blackboard API runtime is disabled.",
    "Shared write is disabled.",
    "Google Sheets write is disabled.",
    "Autonomous execution is disabled.",
    # current safe posture
    "Dashboard read-only / controlled local route behavior.",
    "Worker OFF.",
    "OpenClaw Not Connected.",
    "Hermes Not Connected.",
    "Google Sheets Disabled.",
    "DISPATCH OFF",
    "WORKER OFF",
    "OPENCLAW NOT CONNECTED",
    "HERMES NOT CONNECTED",
    "GOOGLE SHEETS DISABLED",
    "DISPATCH OFF.",
    "WORKER OFF.",
    "OPENCLAW NOT CONNECTED.",
    "HERMES NOT CONNECTED.",
    "GOOGLE SHEETS DISABLED.",
    "No fixture JSON.",
    "No .json artifact.",
    "No mock data file.",
    "No seed data file.",
    "No fixture directory.",
    "No fixture loader runtime.",
    "No preview data loader.",
    "No local mock data preview runtime.",
    "No Final authorization planning runtime.",
    "No Final authorization decision runtime.",
    "No Artifact creation command runtime.",
    "No Blackboard Loop runtime.",
    "No Dashboard badge display runtime.",
    "No Decision audit display runtime.",
    "No Owner review checklist runtime.",
    "No Dashboard preview display runtime.",
    "No local dry-run preview runtime.",
    "No preview renderer runtime.",
    "No loop contract runtime.",
    "No state machine runtime.",
    "No loop scheduler.",
    "No dispatch gate enabled.",
    "No autonomous execution.",
    "No Hermes activation.",
    "No Hermes blackboard mode.",
    "No Hermes runtime.",
    "No Hermes memory store.",
    "No all-conversation logging.",
    "No cleanup demo task.",
    "No cleanup apply.",
    "No --apply.",
    "No task deletion.",
    "No task archive.",
    "No queue DB change.",
    "No local queue data change.",
    "No Replit queue data change.",
    "No real queue DB read.",
    "No POST.",
    "No live local queue write validation.",
    "No Worker execution.",
    "No OpenClaw call.",
    "No Hermes call.",
    "No Google Sheets read.",
    "No Google Sheets write.",
    "No secrets read.",
    "No secrets copied.",
    "No .env created.",
    "No webhook.",
    "No connector.",
    "No external side effects.",
    "No production DB.",
    "No shared DB.",
    "No remote shared DB.",
    "No Remote Blackboard API runtime.",
    "No Dashboard route created.",
    "No Dashboard endpoint created.",
    "No Dashboard template created.",
    "No Dashboard static asset created.",
    "No app route modified.",
    "No template file modified.",
    "No static file modified.",
    "No Core runtime host.",
    "No Worker runtime.",
    "No OpenClaw runtime.",
    "No systemd service.",
    "No daemon.",
    "No Docker deployment.",
    "No queue synchronization.",
    "No queue migration.",
    "No queue backfill.",
    "No queue merge.",
    "No conflict resolver.",
    "No fixture JSON created.",
    "No mock data file created.",
    "No seed data file created.",
    "No fixture directory created.",
    "No tag.",
    # validation summary
    "v0.8.1-K readiness: ALL PASS.",
    "v0.8.1-J readiness: ALL PASS.",
    "v0.8.1-I readiness: ALL PASS.",
    "v0.8.1-H readiness: ALL PASS.",
    "v0.8.1-G readiness: ALL PASS.",
    "v0.8.1-F readiness: ALL PASS.",
    "v0.8.1-E readiness: ALL PASS.",
    "v0.8.1-D readiness: ALL PASS.",
    "v0.8.1-C readiness: ALL PASS.",
    "v0.8.1-B readiness: ALL PASS.",
    "v0.8.1-A readiness: ALL PASS.",
    "v0.8.0-G readiness: ALL PASS.",
    "v0.8.0-F readiness: ALL PASS.",
    "v0.8.0-A readiness: ALL PASS.",
    "v0.7.5-A readiness: ALL PASS.",
    "compileall scripts: PASS.",
    # safety grep summary
    "No real unsafe claim was found.",
    "No real secret was found.",
    "Forbidden field names are allowed planning tokens.",
    "Readiness forbidden-pattern matches are benign.",
    # next recommended step
    "v0.8.1-L — Local Mock Data Fixture JSON Artifact Creation Request Plan",
    "v0.8.1-L must not start unless separately approved by Owner.",
    "v0.8.1-L must not create fixture JSON unless the exact explicit Owner authorization phrase is separately issued by Owner.",
    "v0.8.1-L must not create preview data loader.",
    "v0.8.1-L must not modify Dashboard route/template/static.",
    "v0.8.1-L must not read real queue DB.",
    "v0.8.1-L must not send POST.",
    "v0.8.1-L must not start Worker.",
    "v0.8.1-L must not call OpenClaw.",
    "v0.8.1-L must not activate Hermes.",
    "v0.8.1-L must not read or write Google Sheets.",
]
for token in REQUIRED:
    ok(f"doc 含「{token}」") if token in doc else xx(f"doc 含「{token}」")

# ---------------------------------------------------------------------------
# [4] 禁止包含的不安全聲明 / 機密
#     先移除合法的安全否定句（其字面含 forbidden 子字串），再掃 forbidden。
#     forbidden field 名稱（bare token）為 allowed planning token，僅以 value-form
#     pattern 偵測真實機密，故不會誤判。
# ---------------------------------------------------------------------------
print("[4] 禁止包含的不安全聲明 / 機密")
SAFE_NEGATIONS = [
    "No secrets read.",
    "No secrets copied.",
    "No .env created.",
    "No dispatch gate enabled.",
    "Owner final authorization checklist: no real queue DB read is required.",
    "Owner final rejection checklist: reject final authorization if real queue DB read is required.",
    "Creation-only allowed scope excludes any real queue DB read.",
    "real queue DB read is required.",
    "No real queue DB read.",
    "No fixture JSON created.",
    "No mock data file created.",
    "No seed data file created.",
    "No fixture directory created.",
    "No Google Sheets access is required.",
    "No Google Sheets read.",
    "No Dashboard route created.",
    "No Dashboard endpoint created.",
    "No Dashboard template created.",
    "No Dashboard static asset created.",
    "No app route modified.",
    "No template file modified.",
    "No static file modified.",
]
scrubbed = doc
for phrase in SAFE_NEGATIONS:
    scrubbed = scrubbed.replace(phrase, "")

FORBIDDEN_SUBSTR = [
    "GOOGLE_SHEETS_ENABLED=true",
    "fixture JSON created",
    "fixture directory created",
    "mock data file created",
    "seed data file created",
    "fixture loader runtime created",
    "fixture loader runtime implemented",
    "preview data loader created",
    "preview data loader implemented",
    "local mock data preview runtime created",
    "local mock data preview runtime implemented",
    "Dashboard fixture preview runtime created",
    "Dashboard fixture preview runtime implemented",
    "Final authorization planning runtime created",
    "Final authorization decision runtime created",
    "Artifact creation command runtime created",
    "Blackboard Loop runtime created",
    "Blackboard Loop runtime implemented",
    "Blackboard Loop runtime enabled",
    "Dashboard badge display runtime created",
    "Dashboard preview display runtime created",
    "Dashboard preview display runtime implemented",
    "Dashboard preview display runtime enabled",
    "preview renderer runtime created",
    "Dashboard route created",
    "Dashboard endpoint created",
    "Dashboard template created",
    "Dashboard static asset created",
    "app route modified",
    "template file modified",
    "static file modified",
    "loop contract runtime created",
    "state machine runtime created",
    "loop scheduler created",
    "loop scheduler enabled",
    "dispatch gate enabled",
    "autonomous execution enabled",
    "Worker enabled",
    "Worker started",
    "Worker runtime created",
    "Worker dispatch enabled",
    "OpenClaw connected",
    "OpenClaw called",
    "OpenClaw runtime created",
    "Hermes connected",
    "Hermes activated",
    "Hermes called",
    "Hermes runtime created",
    "Hermes memory store created",
    "Hermes learning runtime created",
    "Hermes blackboard mode enabled",
    "Google Sheets live write enabled",
    "Google Sheets read",
    "Google Sheets written",
    "Remote Blackboard API runtime created",
    "Remote Blackboard API implemented",
    "Remote Blackboard API read enabled",
    "Remote Blackboard API write enabled",
    "production DB created",
    "shared DB created",
    "remote shared DB created",
    "queue DB read",
    "real queue DB read",
    "queue DB modified",
    "local queue data modified",
    "Replit queue data modified",
    "queue migration performed",
    "queue data synchronized",
    "queue data moved",
    "queue data copied",
    "queue data merged",
    "queue data backfilled",
    "conflict resolver implemented",
    "shared write enabled",
    "Blackboard shared write enabled",
    "POST to Replit Preview was sent",
    "POST to real queue was sent",
    "live queue write validation performed",
    "webhook created",
    "webhook receiver created",
    "connector created",
    "external network call added",
    "API route added",
    "FastAPI router added",
    "database client added",
    "migration added",
    "schema migration performed",
    "source-of-truth switch performed",
    "cleanup applied",
    "demo task cleaned up",
    "tasks deleted",
    "tasks archived",
    "apply_allowed = True",
    "apply_requested = True",
    "dry_run = False",
    "external_side_effects = True",
    "approval_is_execution = True",
    "approval_readiness_is_execution = True",
    "dispatch_enabled = True",
    "artifact_creation_permission = True",
    "loader_permission = True",
    "dashboard_change_permission = True",
    "execution_permission = True",
    "dispatch_permission = True",
    "external_side_effects_permission = True",
    "secrets read",
    "secrets copied",
    "secrets created",
    ".env created",
    "credentials moved",
    "tag created",
]
for token in FORBIDDEN_SUBSTR:
    ok(f"doc 無「{token}」") if token not in scrubbed else xx(f"doc 不得含「{token}」")

# value-bearing secret patterns only (bare forbidden-field tokens are allowed planning tokens)
FORBIDDEN_PATTERNS = [
    (r"spreadsheets/d/[A-Za-z0-9_-]{20,}", "real spreadsheet URL"),
    (r'"?refresh_token"?\s*[:=]\s*"[^"]+"', "refresh token value"),
    (r'"?client_secret"?\s*[:=]\s*"[^"]+"', "client secret value"),
    (r'"?private_key"?\s*[:=]\s*"[^"]+"', "private key value"),
    (r"-----BEGIN[ A-Z]*PRIVATE KEY-----", "private key block"),
    (r'"?spreadsheet_id"?\s*[:=]\s*"[A-Za-z0-9_-]{20,}"', "spreadsheet id value"),
    (r"dashboard_token\s*=\s*[A-Za-z0-9_\-]{8,}", "dashboard token value"),
]
for pat, label in FORBIDDEN_PATTERNS:
    found = bool(re.search(pat, doc, re.IGNORECASE))
    ok(f"doc 無「{label}」") if not found else xx(f"doc 不得含「{label}」")

# ---------------------------------------------------------------------------
# 結果
# ---------------------------------------------------------------------------
total = len(PASS) + len(FAIL)
print(f"\n合計：{len(PASS)}/{total} 通過")
if FAIL:
    print(f"\nXX v0.8.1-K readiness 失敗 {len(FAIL)} 項：")
    for f in FAIL:
        print(f"   - {f}")
    sys.exit(1)
else:
    print(
        "\nv0.8.1-K Local Mock Data Fixture JSON Artifact Creation Final Authorization Plan readiness: ALL PASS"
    )
    sys.exit(0)
