"""v0.8.1-J readiness check: Local Mock Data Fixture JSON Artifact Creation Authorization Review (plan-first / authorization-review-only).

Authorization-review verification. Checks that the v0.8.1-J plan document exists and contains the
required sections (1-65), the current-master marker, the v0.8.1-J plan-first /
authorization-review-only markers, the relationship-to-v0.8.1-I and relationship-to-v0.8.1-H
markers, the problem-statement markers, the Local Mock Data Fixture JSON Artifact Creation
Authorization Review definition markers, the authorization review / fixture JSON artifact
prohibition boundary markers, the review input / review output boundary markers, the explicit Owner
authorization phrase relationship markers, the candidate artifact path / filename / schema version
review markers, the candidate top-level shape / records collection / record count / ordering review
markers, the synthetic local-only / no-real-data readiness review markers, the required fields /
forbidden fields / boolean safety invariant review markers, the message family readiness review
markers, the per-family readiness review markers (Mock Task / Decision / Result / Advice Message,
Mock Badge Status, Mock Runtime-off Status), the display copy / safety notes / next owner action /
audit notes / rollback notes readiness review markers, the future creation authorization readiness /
future artifact creation command / validation / rollback / read-only loader / Dashboard preview
boundary markers, the Dashboard route / template / static boundary markers, the app / runtime
boundary markers, the queue and real data boundary markers, the Remote Blackboard API relationship
markers, the Worker / OpenClaw / Hermes separation markers, the Google Sheets boundary markers, the
secrets / privacy / memory boundary markers, the network / webhook / connector boundary markers, the
failure / rollback / audit boundary markers, the authorization review / rejection review checklist
markers, the authorization review record blueprint markers, the authorization review validation
checklist markers, the forbidden fields rejection checklist markers, the boolean safety invariant
checklist markers, the message family review checklist markers, the disabled runtime list markers,
the current safe posture markers, the validation summary markers, the safety grep summary markers,
and the next recommended step (v0.8.1-K) — and that it asserts no unsafe "implemented / created /
added / enabled / activated / connected / called / started / written / read / modified / moved /
migrated" claim, no artifact-creation / loader / dashboard-change / execution / dispatch /
external-side-effects permission grant, and contains no real secret value.

The document is allowed to contain safe negations and forbidden-field planning tokens (bare field
names such as refresh_token / client_secret / private_key / spreadsheet_id, listed in the Forbidden
fields rejection checklist). Safe negations that literally embed a forbidden substring are scrubbed
before the forbidden scan; the secret patterns only match value-bearing forms (name = "value"), so
bare planning tokens are not mis-flagged.

This script only reads the plan document. It does NOT read .env, credentials, tokens, or secrets,
makes no network call, imports no app logic (no app.main, no QueueStore), adds no API route /
router / Dashboard route / template / static / database client / migration, creates no production /
shared DB, creates no fixture JSON, no .json artifact, no mock data file, no seed data file, no
fixture directory, no preview data loader, builds no fixture loader runtime, no Dashboard preview
display runtime, reads no real queue DB, writes no queue, sends no POST, starts no Worker, connects
no OpenClaw, activates no Hermes, opens no shared write, and reads/writes no Google Sheets.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
PASS = []
FAIL = []

DOC_PATH = (
    ROOT
    / "docs"
    / "HERMES_OPENCLAW_LOCAL_MOCK_DATA_FIXTURE_JSON_ARTIFACT_CREATION_AUTHORIZATION_REVIEW_V0_8_1_J.md"
)


def ok(label):
    PASS.append(label)
    print(f"  ok : {label}")


def xx(label):
    FAIL.append(label)
    print(f"  XX : {label}")


# ---------------------------------------------------------------------------
# [1] plan 文件存在
# ---------------------------------------------------------------------------
print("[1] plan 文件存在")
ok("v0.8.1-J plan doc 存在") if DOC_PATH.exists() else xx("v0.8.1-J plan doc 存在")
if not DOC_PATH.exists():
    print("\nXX plan doc 不存在，無法繼續")
    sys.exit(1)

doc = DOC_PATH.read_text(encoding="utf-8")

# ---------------------------------------------------------------------------
# [2] 必須包含的章節（1-65）
# ---------------------------------------------------------------------------
print("[2] 必須包含的章節")
REQUIRED_SECTIONS = [
    "1. Purpose",
    "2. Current master",
    "3. Scope",
    "4. Relationship to v0.8.1-I Local Mock Data Fixture JSON Artifact Creation Plan",
    "5. Relationship to v0.8.1-H Local Mock Data Fixture JSON Creation Authorization Plan",
    "6. Problem statement",
    "7. Local Mock Data Fixture JSON Artifact Creation Authorization Review definition",
    "8. Authorization review boundary",
    "9. Fixture JSON artifact prohibition boundary",
    "10. Review input boundary",
    "11. Review output boundary",
    "12. Explicit Owner authorization phrase relationship",
    "13. Candidate artifact path review",
    "14. Candidate artifact filename review",
    "15. Candidate schema version review",
    "16. Candidate top-level shape review",
    "17. Candidate records collection review",
    "18. Candidate record count review",
    "19. Candidate record ordering review",
    "20. Synthetic local-only readiness review",
    "21. No-real-data readiness review",
    "22. Required fields review",
    "23. Forbidden fields review",
    "24. Boolean safety invariant review",
    "25. Message family readiness review",
    "26. Mock Task Message readiness review",
    "27. Mock Decision Message readiness review",
    "28. Mock Result Message readiness review",
    "29. Mock Advice Message readiness review",
    "30. Mock Badge Status readiness review",
    "31. Mock Runtime-off Status readiness review",
    "32. Display copy readiness review",
    "33. Safety notes readiness review",
    "34. Next owner action readiness review",
    "35. Audit notes readiness review",
    "36. Rollback notes readiness review",
    "37. Future creation authorization readiness",
    "38. Future artifact creation command boundary",
    "39. Future artifact validation boundary",
    "40. Future artifact rollback boundary",
    "41. Future read-only loader boundary",
    "42. Future Dashboard preview boundary",
    "43. Dashboard route / template / static boundary",
    "44. App / runtime boundary",
    "45. Queue and real data boundary",
    "46. Remote Blackboard API relationship",
    "47. Worker / OpenClaw / Hermes separation boundary",
    "48. Google Sheets boundary",
    "49. Secrets / privacy / memory boundary",
    "50. Network / webhook / connector boundary",
    "51. Failure / rollback / audit boundary",
    "52. Authorization review checklist",
    "53. Authorization rejection review checklist",
    "54. Authorization review record blueprint",
    "55. Authorization review validation checklist",
    "56. Forbidden fields rejection checklist",
    "57. Boolean safety invariant checklist",
    "58. Message family review checklist",
    "59. Disabled runtime list",
    "60. Current safe system posture",
    "61. Validation summary",
    "62. Safety grep summary",
    "63. Non-goals",
    "64. Acceptance criteria",
    "65. Next recommended step",
]
for section in REQUIRED_SECTIONS:
    ok(f"doc 含章節「{section}」") if section in doc else xx(f"doc 含章節「{section}」")

# ---------------------------------------------------------------------------
# [3] 必須包含的 markers
# ---------------------------------------------------------------------------
print("[3] 必須包含的 markers")
REQUIRED = [
    # version
    "v0.8.1-J",
    "Local Mock Data Fixture JSON Artifact Creation Authorization Review",
    # current master
    "HEAD = origin/master = e437f8c904c6ba69b24bcf9fd5418618f091356f",
    "docs: plan local mock data fixture json artifact creation",
    # v0.8.1-J plan-first / authorization-review-only markers
    "v0.8.1-J Local Mock Data Fixture JSON Artifact Creation Authorization Review is plan-first.",
    "v0.8.1-J Local Mock Data Fixture JSON Artifact Creation Authorization Review is authorization-review-only.",
    "v0.8.1-J does not create fixture JSON.",
    "v0.8.1-J does not create .json artifact.",
    "v0.8.1-J does not create mock data file.",
    "v0.8.1-J does not create seed data file.",
    "v0.8.1-J does not create fixture directory.",
    "v0.8.1-J does not create preview data loader.",
    "v0.8.1-J does not implement fixture loader runtime.",
    "v0.8.1-J does not implement Dashboard preview display runtime.",
    "v0.8.1-J does not implement local mock data preview runtime.",
    "v0.8.1-J does not create Dashboard route.",
    "v0.8.1-J does not create Dashboard endpoint.",
    "v0.8.1-J does not create Dashboard template.",
    "v0.8.1-J does not create Dashboard static asset.",
    "v0.8.1-J does not modify app.",
    "v0.8.1-J does not modify templates.",
    "v0.8.1-J does not modify static.",
    "v0.8.1-J does not read real queue DB.",
    "v0.8.1-J does not write queue data.",
    "v0.8.1-J does not send POST.",
    "v0.8.1-J does not start Worker.",
    "v0.8.1-J does not connect OpenClaw.",
    "v0.8.1-J does not activate Hermes.",
    "v0.8.1-J does not connect Hermes.",
    "v0.8.1-J does not read Google Sheets.",
    "v0.8.1-J does not write Google Sheets.",
    "v0.8.1-J does not read secrets.",
    "v0.8.1-J does not create .env.",
    "v0.8.1-J does not create webhook.",
    "v0.8.1-J does not create connector.",
    "v0.8.1-J does not create Remote Blackboard API runtime.",
    "v0.8.1-J does not create production DB.",
    "v0.8.1-J does not create shared DB.",
    "v0.8.1-J does not open shared write.",
    # relationship to v0.8.1-I
    "v0.8.1-I Local Mock Data Fixture JSON Artifact Creation Plan is complete.",
    "v0.8.1-J starts the Local Mock Data Fixture JSON Artifact Creation Authorization Review step.",
    "v0.8.1-J builds on Local Mock Data Fixture JSON Artifact Creation planning.",
    "v0.8.1-J reviews whether the artifact creation blueprint is ready for a future Owner authorization decision.",
    "v0.8.1-J preserves Owner final approval authority.",
    "v0.8.1-J preserves decision and dispatch separation.",
    "v0.8.1-J preserves audit trail.",
    "v0.8.1-J preserves dispatch-disabled boundary.",
    "v0.8.1-J preserves local mock data preview boundary.",
    "v0.8.1-J preserves the fixture contract boundary.",
    "v0.8.1-J preserves the fixture draft boundary.",
    "v0.8.1-J preserves the fixture JSON approval boundary.",
    "v0.8.1-J preserves the fixture JSON creation boundary.",
    "v0.8.1-J preserves the candidate artifact planning boundary.",
    "v0.8.1-J preserves the artifact owner approval boundary.",
    "v0.8.1-J preserves the creation authorization boundary.",
    "v0.8.1-J preserves the artifact creation plan boundary.",
    "v0.8.1-J preserves read-only Dashboard display boundary.",
    "v0.8.1-J does not change any v0.8.1-I boundary.",
    "v0.8.1-J does not change any v0.8.1-H boundary.",
    "v0.8.1-J does not change any v0.8.1-G boundary.",
    "v0.8.1-J does not change any v0.8.1-F boundary.",
    "v0.8.1-J does not change any v0.8.1-E boundary.",
    "v0.8.1-J does not change any v0.8.1-D boundary.",
    "v0.8.1-J does not change any v0.8.1-C boundary.",
    "v0.8.1-J does not change any v0.8.1-B boundary.",
    "v0.8.1-J does not change any v0.8.1-A boundary.",
    "v0.8.1-J does not change any v0.8.0-G boundary.",
    "v0.8.1-J does not change any v0.8.0-F boundary.",
    # relationship to v0.8.1-H
    "v0.8.1-H defined the future explicit Owner authorization phrase.",
    "v0.8.1-J does not issue the explicit Owner authorization phrase.",
    "v0.8.1-J does not satisfy the explicit Owner authorization phrase.",
    "v0.8.1-J does not convert review readiness into artifact creation permission.",
    "v0.8.1-J does not convert review readiness into execution permission.",
    "v0.8.1-J does not convert review readiness into dispatch permission.",
    # definition
    "Local Mock Data Fixture JSON Artifact Creation Authorization Review means the planning-only audit of",
    "Local Mock Data Fixture JSON Artifact Creation Authorization Review is a planning artifact in v0.8.1-J.",
    "Local Mock Data Fixture JSON Artifact Creation Authorization Review is not runtime code.",
    "Local Mock Data Fixture JSON Artifact Creation Authorization Review is not a fixture JSON file.",
    "Local Mock Data Fixture JSON Artifact Creation Authorization Review is not a mock data file.",
    "Local Mock Data Fixture JSON Artifact Creation Authorization Review is not a preview data loader.",
    "Local Mock Data Fixture JSON Artifact Creation Authorization Review requires separate future plan and Owner approval before artifact creation.",
    # safety principles
    "Approval is not execution.",
    "Approval readiness is not execution permission.",
    "Owner approval is not dispatch permission.",
    "Creation authorization is not execution permission.",
    "Artifact creation authorization review is not artifact creation.",
    "Artifact creation authorization review is not fixture JSON creation.",
    "Artifact creation authorization review is not mock data file creation.",
    "Artifact creation authorization review is not execution permission.",
    "Artifact creation authorization review is not Worker dispatch.",
    "Artifact creation authorization review is not OpenClaw call.",
    "Artifact creation authorization review is not Hermes action.",
    "Artifact creation authorization review must not read real queue DB.",
    "Artifact creation authorization review must not send POST.",
    "Artifact creation authorization review must not create fixture JSON.",
    "Artifact creation authorization review must not create preview data loader.",
    "Decision and dispatch remain separate.",
    "Dashboard preview display is read-only.",
    # authorization review boundary
    "Authorization review boundary is planning only.",
    "Authorization review is expressed as text and pseudo-field descriptions only.",
    "No authorization review runtime is implemented in v0.8.1-J.",
    "Review readiness does not grant artifact creation permission.",
    # fixture JSON artifact prohibition boundary
    "Fixture JSON artifact prohibition boundary is planning only.",
    "No fixture JSON is created in v0.8.1-J.",
    "No .json artifact is created in v0.8.1-J.",
    "No JSON object is created in v0.8.1-J.",
    "Fixture JSON artifact creation requires separate Owner authorization.",
    # review input boundary
    "Review input boundary is planning only.",
    "Review inputs are the v0.8.1-I artifact blueprint and the v0.8.1-H authorization relationship.",
    "Review inputs are read as planning text only.",
    "Review inputs do not include real queue DB.",
    "Review inputs do not include Google Sheets.",
    "Review inputs do not include secrets.",
    "No review input runtime is implemented in v0.8.1-J.",
    # review output boundary
    "Review output boundary is planning only.",
    "Review output is a planning-only authorization review record blueprint.",
    "Review output is not a fixture JSON file.",
    "Review output is not a mock data file.",
    "Review output is not a loader.",
    "Review output does not grant artifact creation permission.",
    "Review output does not grant execution permission.",
    "Review output does not grant dispatch permission.",
    "No review output runtime is implemented in v0.8.1-J.",
    # explicit Owner authorization phrase relationship
    "Explicit Owner authorization phrase relationship is planning only.",
    "The future explicit Owner authorization phrase from v0.8.1-H must be separately issued before any artifact is created.",
    "The explicit Owner authorization phrase is not issued in v0.8.1-J.",
    "The explicit Owner authorization phrase is not satisfied in v0.8.1-J.",
    "No fixture JSON may be created from v0.8.1-J.",
    # candidate artifact path review
    "Candidate fixture JSON path: fixtures/local_mock_data/hermes_openclaw_local_mock_messages_v0_8_1.json",
    "Candidate fixture JSON path review is planning only.",
    "Candidate fixture JSON path is not created in v0.8.1-J.",
    "Candidate fixture directory is not created in v0.8.1-J.",
    "Candidate fixture JSON file is not created in v0.8.1-J.",
    "Candidate artifact path is inherited from v0.8.1-I planning.",
    # candidate artifact filename review
    "Candidate fixture JSON filename: hermes_openclaw_local_mock_messages_v0_8_1.json",
    "Candidate fixture JSON filename review is planning only.",
    "Candidate fixture JSON filename is not created in v0.8.1-J.",
    # candidate schema version review
    "Candidate fixture JSON schema_version: v0.8.1-local-mock-1.",
    "Candidate schema version review is planning only.",
    "Candidate schema version is not implemented in v0.8.1-J.",
    "No schema migration is performed in v0.8.1-J.",
    # candidate top-level shape review
    "Candidate top-level shape review is planning only.",
    "Candidate top-level shape may include schema_version.",
    "Candidate top-level shape may include fixture_id.",
    "Candidate top-level shape may include is_mock.",
    "Candidate top-level shape may include created_for.",
    "Candidate top-level shape may include records.",
    # candidate records collection review
    "Candidate records collection review is planning only.",
    "Candidate records collection may include six synthetic local-only records.",
    "Candidate records collection must not include real queue data.",
    "Candidate records collection must not include real user data.",
    "Candidate records collection must not include secrets.",
    "Candidate records collection must not include endpoints.",
    "No records collection is created in v0.8.1-J.",
    # candidate record count review
    "Candidate record count review: six records.",
    "Candidate record count review is planning only.",
    "No record is created in v0.8.1-J.",
    # candidate record ordering review
    "Candidate record ordering review: Mock Task Message first.",
    "Candidate record ordering review: Mock Decision Message second.",
    "Candidate record ordering review: Mock Result Message third.",
    "Candidate record ordering review: Mock Advice Message fourth.",
    "Candidate record ordering review: Mock Badge Status fifth.",
    "Candidate record ordering review: Mock Runtime-off Status sixth.",
    "Candidate record ordering review is planning only.",
    # synthetic local-only readiness review
    "Synthetic local-only readiness review: all candidate values must be synthetic.",
    "Synthetic local-only readiness review: all candidate values must be local-only.",
    "Synthetic local-only readiness review: no value may be copied from real queue DB.",
    "Synthetic local-only readiness review: no value may be copied from Google Sheets.",
    "Synthetic local-only readiness review: no value may be copied from secrets.",
    "Synthetic local-only readiness review: no value may be copied from production logs.",
    "Synthetic local-only readiness review: no value may be copied from private user data.",
    "No real data is used in v0.8.1-J.",
    # no-real-data readiness review
    "No-real-data readiness review: future artifact must contain no real queue IDs.",
    "No-real-data readiness review: future artifact must contain no real task IDs.",
    "No-real-data readiness review: future artifact must contain no real user data.",
    "No-real-data readiness review: future artifact must contain no spreadsheet IDs.",
    "No-real-data readiness review: future artifact must contain no tokens.",
    "No-real-data readiness review: future artifact must contain no secrets.",
    "No-real-data readiness review: future artifact must contain no endpoints.",
    # required fields review
    "Required fields review is planning only.",
    "fixture_id",
    "schema_version",
    "is_mock",
    "message_family",
    "message_id",
    "preview_id",
    "created_for",
    "display_title",
    "display_summary",
    "safety_notes",
    "next_owner_action",
    "audit_notes",
    "rollback_notes",
    "No required field is implemented in v0.8.1-J.",
    # forbidden fields review
    "Forbidden fields review is planning only.",
    "real_queue_id",
    "real_task_id",
    "real_user_secret",
    "spreadsheet_id",
    "refresh_token",
    "client_secret",
    "private_key",
    "webhook_url",
    "openclaw_endpoint",
    "hermes_endpoint",
    "production_db_url",
    "remote_blackboard_api_url",
    "No forbidden field value is included in v0.8.1-J.",
    # boolean safety invariant review
    "is_mock = true",
    "dispatch_enabled = false",
    "worker_running = false",
    "openclaw_connected = false",
    "hermes_connected = false",
    "google_sheets_enabled = false",
    "external_side_effects = false",
    "approval_is_execution = false",
    "approval_readiness_is_execution = false",
    "artifact_creation_permission = false",
    "loader_permission = false",
    "dashboard_change_permission = false",
    "execution_permission = false",
    "dispatch_permission = false",
    "external_side_effects_permission = false",
    "No boolean safety invariant runtime is implemented in v0.8.1-J.",
    # message families
    "Mock Task Message",
    "Mock Decision Message",
    "Mock Result Message",
    "Mock Advice Message",
    "Mock Badge Status",
    "Mock Runtime-off Status",
    # per-family readiness review
    "Mock Task Message readiness review is planning only.",
    "Mock Task Message display_title candidate is reviewed.",
    "Mock Task Message display_summary candidate is reviewed.",
    "Mock Task Message safety_notes candidate is reviewed.",
    "Mock Task Message next_owner_action candidate is reviewed.",
    "No Mock Task Message record is created in v0.8.1-J.",
    "Mock Decision Message readiness review is planning only.",
    "Mock Decision Message display_title candidate is reviewed.",
    "Mock Decision Message display_summary candidate is reviewed.",
    "Mock Decision Message safety_notes candidate is reviewed.",
    "Mock Decision Message next_owner_action candidate is reviewed.",
    "No Mock Decision Message record is created in v0.8.1-J.",
    "Mock Result Message readiness review is planning only.",
    "Mock Result Message display_title candidate is reviewed.",
    "Mock Result Message display_summary candidate is reviewed.",
    "Mock Result Message safety_notes candidate is reviewed.",
    "Mock Result Message next_owner_action candidate is reviewed.",
    "No Mock Result Message record is created in v0.8.1-J.",
    "Mock Advice Message readiness review is planning only.",
    "Mock Advice Message display_title candidate is reviewed.",
    "Mock Advice Message display_summary candidate is reviewed.",
    "Mock Advice Message safety_notes candidate is reviewed.",
    "Mock Advice Message next_owner_action candidate is reviewed.",
    "No Mock Advice Message record is created in v0.8.1-J.",
    "Mock Badge Status readiness review is planning only.",
    "Mock Badge Status display_title candidate is reviewed.",
    "Mock Badge Status display_summary candidate is reviewed.",
    "Mock Badge Status safety_notes candidate is reviewed.",
    "Mock Badge Status next_owner_action candidate is reviewed.",
    "No Mock Badge Status record is created in v0.8.1-J.",
    "Mock Runtime-off Status readiness review is planning only.",
    "Mock Runtime-off Status display_title candidate is reviewed.",
    "Mock Runtime-off Status display_summary candidate is reviewed.",
    "Mock Runtime-off Status safety_notes candidate is reviewed.",
    "Mock Runtime-off Status next_owner_action candidate is reviewed.",
    "No Mock Runtime-off Status record is created in v0.8.1-J.",
    # display copy / safety notes / next owner action / audit notes / rollback notes readiness review
    "Display copy readiness review is planning only.",
    "Safety notes readiness review is planning only.",
    "Next owner action readiness review is planning only.",
    "Audit notes readiness review is planning only.",
    "Rollback notes readiness review is planning only.",
    # future creation authorization readiness
    "Future creation authorization readiness is planning only.",
    "Future creation authorization readiness does not create fixture JSON.",
    "Future creation authorization readiness does not grant artifact creation permission.",
    "Future creation authorization readiness does not grant loader permission.",
    "Future creation authorization readiness does not grant Dashboard change permission.",
    "Future creation authorization readiness does not grant execution permission.",
    "Future creation authorization readiness does not grant dispatch permission.",
    "Future creation authorization readiness does not grant external side effects permission.",
    # future artifact creation command boundary
    "Future artifact creation command boundary is planning only.",
    "Future artifact creation command must be separately Owner-authorized.",
    "Future artifact creation command must create only the synthetic local-only fixture JSON file.",
    "Future artifact creation command must not create a loader.",
    "Future artifact creation command must not modify Dashboard route/template/static.",
    "Future artifact creation command must not read real queue DB.",
    "Future artifact creation command must not send POST.",
    "Future artifact creation command must not start Worker.",
    "Future artifact creation command must not call OpenClaw.",
    "Future artifact creation command must not activate Hermes.",
    "Future artifact creation command must not read or write Google Sheets.",
    "No artifact creation command runtime is implemented in v0.8.1-J.",
    # future artifact validation boundary
    "Future artifact validation boundary is planning only.",
    "Future artifact must validate as synthetic local-only before any use.",
    "Future artifact must contain only approved message families.",
    "Future artifact must contain only approved required fields.",
    "Future artifact must contain no forbidden fields.",
    "Future artifact must satisfy boolean safety invariants.",
    "No artifact validation runtime is implemented in v0.8.1-J.",
    # future artifact rollback boundary
    "Future artifact rollback boundary is planning only.",
    "Future artifact must be removable by deleting only the approved local fixture JSON file.",
    "Future artifact rollback must not require database migration.",
    "Future artifact rollback must not require real queue DB write.",
    "Future artifact rollback must not require POST.",
    "No artifact rollback runtime is implemented in v0.8.1-J.",
    # future read-only loader boundary
    "A future read-only loader may read the approved fixture once it exists.",
    "Future read-only loader is display-only.",
    "Future read-only loader is not execution permission.",
    "Future read-only loader must not write the fixture.",
    "Future read-only loader must not read real queue DB.",
    "Future read-only loader must not send POST.",
    "No read-only loader runtime is implemented in v0.8.1-J.",
    "No preview data loader is implemented in v0.8.1-J.",
    # future Dashboard preview boundary
    "Dashboard may eventually display the approved local mock data fixture once created.",
    "Future Dashboard preview is display-only.",
    "No Dashboard fixture preview runtime is implemented in v0.8.1-J.",
    # Dashboard route / template / static boundary
    "Dashboard route boundary is planning only.",
    "No Dashboard route is created in v0.8.1-J.",
    "No Dashboard endpoint is created in v0.8.1-J.",
    "No Dashboard template is created in v0.8.1-J.",
    "No Dashboard static asset is created in v0.8.1-J.",
    "No app route is modified in v0.8.1-J.",
    "No template file is modified in v0.8.1-J.",
    "No static file is modified in v0.8.1-J.",
    # app / runtime boundary
    "App / runtime boundary is planning only.",
    "No app module is modified in v0.8.1-J.",
    "No app.main import is performed in v0.8.1-J.",
    "No QueueStore import is performed in v0.8.1-J.",
    "No runtime host is created in v0.8.1-J.",
    "No daemon is created in v0.8.1-J.",
    "No systemd service is created in v0.8.1-J.",
    "No Docker deployment is created in v0.8.1-J.",
    "No fixture loader runtime is created in v0.8.1-J.",
    # queue and real data boundary
    "No source-of-truth switch is performed.",
    "No queue DB change.",
    "No local queue data change.",
    "No Replit queue data change.",
    "No real queue DB read.",
    "No queue migration is performed.",
    "No queue synchronization is performed.",
    "No queue backfill is performed.",
    "No queue merge is performed.",
    "No conflict resolver is implemented.",
    "No shared write is enabled.",
    # Remote Blackboard API relationship
    "Remote Blackboard API remains planning only.",
    "Remote Blackboard API runtime is not implemented in v0.8.1-J.",
    "Remote Blackboard API read is not enabled in v0.8.1-J.",
    "Remote Blackboard API write is not enabled in v0.8.1-J.",
    "Remote Blackboard API is not required for artifact creation authorization review.",
    # separation
    "Worker remains OFF.",
    "OpenClaw remains Not Connected.",
    "Hermes remains Not Connected.",
    "Worker is dispatch runtime.",
    "OpenClaw is execution / gateway / tools layer.",
    "Hermes is strategy / proxy / memory layer.",
    "Worker must not run from plan-only authorization review.",
    "OpenClaw must not execute from plan-only authorization review.",
    "Hermes must not act from plan-only authorization review.",
    # Google Sheets boundary
    "Google Sheets remains Disabled.",
    "No Google Sheets access is required.",
    "No Google Sheets write is performed.",
    "No Google Sheets live write is enabled.",
    # secrets / privacy / memory boundary
    "No secrets are read.",
    "No secrets are copied.",
    "No secrets are created.",
    "No .env file is created.",
    "No credentials are moved.",
    "No production secrets are copied.",
    "No Hermes memory store is created.",
    "No Hermes learning runtime is created.",
    "No private conversation log is created.",
    "No all-conversation logging is enabled.",
    # network / webhook / connector boundary
    "No webhook is created.",
    "No webhook receiver is created.",
    "No connector is created.",
    "No external network call is added.",
    "No inbound listener is added.",
    "No outbound integration is added.",
    "No port exposure is configured.",
    "No POST is sent.",
    "No live queue write validation is performed.",
    # failure / rollback / audit boundary
    "Failure / rollback / audit boundary is planning only.",
    "On any doubt, stop and ask Owner.",
    "Rollback of v0.8.1-J is deleting only the two planning files.",
    "Audit trail is preserved.",
    # authorization review checklist
    "Authorization review checklist: v0.8.1-I artifact blueprint is reviewed.",
    "Authorization review checklist: v0.8.1-H explicit Owner authorization phrase relationship is reviewed.",
    "Authorization review checklist: candidate artifact path is reviewed.",
    "Authorization review checklist: candidate filename is reviewed.",
    "Authorization review checklist: candidate schema_version is reviewed.",
    "Authorization review checklist: candidate top-level shape is reviewed.",
    "Authorization review checklist: candidate records collection is reviewed.",
    "Authorization review checklist: candidate record count is reviewed.",
    "Authorization review checklist: candidate record ordering is reviewed.",
    "Authorization review checklist: synthetic local-only readiness is reviewed.",
    "Authorization review checklist: no-real-data readiness is reviewed.",
    "Authorization review checklist: required fields are reviewed.",
    "Authorization review checklist: forbidden fields are reviewed.",
    "Authorization review checklist: boolean safety invariants are reviewed.",
    "Authorization review checklist: message families are reviewed.",
    "Authorization review checklist: per-record blueprints are reviewed.",
    "Authorization review checklist: no loader is authorized.",
    "Authorization review checklist: no Dashboard change is authorized.",
    "Authorization review checklist: no real queue DB read is required.",
    "Authorization review checklist: no POST is required.",
    "Authorization review checklist: no Worker/OpenClaw/Hermes action is required.",
    "Authorization review checklist: no Google Sheets access is required.",
    "Authorization review checklist: no secrets access is required.",
    "Authorization review checklist: review readiness does not grant artifact creation permission.",
    # authorization rejection review checklist
    "Authorization rejection review checklist: reject review readiness if v0.8.1-I artifact blueprint is missing.",
    "Authorization rejection review checklist: reject review readiness if explicit Owner authorization phrase relationship is unclear.",
    "Authorization rejection review checklist: reject review readiness if forbidden fields are present.",
    "Authorization rejection review checklist: reject review readiness if boolean safety invariants are unsafe.",
    "Authorization rejection review checklist: reject review readiness if loader permission is requested.",
    "Authorization rejection review checklist: reject review readiness if Dashboard change permission is requested.",
    "Authorization rejection review checklist: reject review readiness if execution permission is requested.",
    "Authorization rejection review checklist: reject review readiness if dispatch permission is requested.",
    "Authorization rejection review checklist: reject review readiness if external side effects are requested.",
    "Authorization rejection review checklist: reject review readiness if real queue DB read is required.",
    "Authorization rejection review checklist: reject review readiness if POST is required.",
    "Authorization rejection review checklist: reject review readiness if Worker/OpenClaw/Hermes action is required.",
    "Authorization rejection review checklist: reject review readiness if Google Sheets access is required.",
    "Authorization rejection review checklist: reject review readiness if secrets access is required.",
    # authorization review record blueprint
    "Authorization review record blueprint is planning only.",
    "Authorization review record may include review_id.",
    "Authorization review record may include reviewed_plan_version.",
    "Authorization review record may include reviewed_authorization_version.",
    "Authorization review record may include candidate_fixture_path.",
    "Authorization review record may include candidate_schema_version.",
    "Authorization review record may include blueprint_complete.",
    "Authorization review record may include synthetic_local_only_ready.",
    "Authorization review record may include no_real_data_ready.",
    "Authorization review record may include required_fields_ready.",
    "Authorization review record may include forbidden_fields_absent.",
    "Authorization review record may include boolean_invariants_safe.",
    "Authorization review record may include message_families_ready.",
    "Authorization review record may include per_record_blueprints_ready.",
    "Authorization review record may include review_result.",
    "Authorization review record may include owner_notes.",
    "Authorization review record may include rollback_notes.",
    "Authorization review record may include artifact_creation_permission.",
    "Authorization review record may include execution_permission.",
    "Authorization review record may include dispatch_permission.",
    "Authorization review record may include external_side_effects_permission.",
    "No Authorization review record is created in v0.8.1-J.",
    "Authorization review result value: blueprint_ready_for_future_creation_authorization.",
    "Authorization review result value: blueprint_not_ready_for_future_creation_authorization.",
    "Authorization review result value: request_revision.",
    "Authorization review result value: defer_review.",
    "Authorization review result values are planning only.",
    "No Authorization review decision runtime is implemented in v0.8.1-J.",
    # authorization review validation checklist
    "Validation checklist: authorization review must remain synthetic local-only.",
    "Validation checklist: authorization review must contain no fixture JSON.",
    "Validation checklist: authorization review must contain no JSON object.",
    "Validation checklist: authorization review must contain no mock data file.",
    "Validation checklist: authorization review must contain no fixture directory.",
    "Validation checklist: authorization review must contain no preview data loader.",
    "Validation checklist: authorization review must contain no runtime.",
    "Validation checklist: authorization review must contain no forbidden field values.",
    "Validation checklist: authorization review must satisfy boolean safety invariants.",
    "Validation checklist: authorization review must keep artifact_creation_permission = false.",
    "Validation checklist: authorization review must keep loader_permission = false.",
    "Validation checklist: authorization review must keep dashboard_change_permission = false.",
    "Validation checklist: authorization review must not enable dispatch.",
    "Validation checklist: authorization review must not enable Worker.",
    "Validation checklist: authorization review must not connect OpenClaw.",
    "Validation checklist: authorization review must not activate Hermes.",
    "Validation checklist: authorization review must not enable Google Sheets.",
    "Validation checklist: authorization review must not read real queue DB.",
    "Validation checklist: authorization review must not send POST.",
    "Validation checklist: authorization review must not read secrets.",
    # forbidden field rejection checklist
    "Forbidden field rejection checklist: reject if real_queue_id appears as a field.",
    "Forbidden field rejection checklist: reject if real_task_id appears as a field.",
    "Forbidden field rejection checklist: reject if real_user_secret appears as a field.",
    "Forbidden field rejection checklist: reject if spreadsheet_id appears as a field.",
    "Forbidden field rejection checklist: reject if refresh_token appears as a field.",
    "Forbidden field rejection checklist: reject if client_secret appears as a field.",
    "Forbidden field rejection checklist: reject if private_key appears as a field.",
    "Forbidden field rejection checklist: reject if webhook_url appears as a field.",
    "Forbidden field rejection checklist: reject if openclaw_endpoint appears as a field.",
    "Forbidden field rejection checklist: reject if hermes_endpoint appears as a field.",
    "Forbidden field rejection checklist: reject if production_db_url appears as a field.",
    "Forbidden field rejection checklist: reject if remote_blackboard_api_url appears as a field.",
    # boolean safety invariant checklist
    "Boolean safety invariant checklist is planning only.",
    "Boolean safety invariant checklist: is_mock = true.",
    "Boolean safety invariant checklist: artifact_creation_permission = false.",
    "Boolean safety invariant checklist: loader_permission = false.",
    "Boolean safety invariant checklist: dashboard_change_permission = false.",
    "Boolean safety invariant checklist: execution_permission = false.",
    "Boolean safety invariant checklist: dispatch_permission = false.",
    "Boolean safety invariant checklist: external_side_effects_permission = false.",
    # message family review checklist
    "Message family review checklist is planning only.",
    "Message family review checklist: Mock Task Message readiness review is reviewed.",
    "Message family review checklist: Mock Decision Message readiness review is reviewed.",
    "Message family review checklist: Mock Result Message readiness review is reviewed.",
    "Message family review checklist: Mock Advice Message readiness review is reviewed.",
    "Message family review checklist: Mock Badge Status readiness review is reviewed.",
    "Message family review checklist: Mock Runtime-off Status readiness review is reviewed.",
    "No message family record is created in v0.8.1-J.",
    # disabled runtime list
    "Authorization review runtime is disabled.",
    "Authorization review decision runtime is disabled.",
    "Artifact creation planning runtime is disabled.",
    "Artifact creation command runtime is disabled.",
    "Fixture JSON creation authorization planning runtime is disabled.",
    "Fixture loader runtime is disabled.",
    "Preview data loader runtime is disabled.",
    "Local mock data preview runtime is disabled.",
    "Dashboard fixture preview runtime is disabled.",
    "Blackboard Loop runtime is disabled.",
    "Dashboard badge display runtime is disabled.",
    "Decision audit display runtime is disabled.",
    "Owner review checklist runtime is disabled.",
    "Dashboard preview display runtime is disabled.",
    "Dispatch gate is disabled.",
    "Worker runtime is disabled.",
    "OpenClaw runtime is disabled.",
    "Hermes runtime is disabled.",
    "Remote Blackboard API runtime is disabled.",
    "Shared write is disabled.",
    "Google Sheets write is disabled.",
    "Autonomous execution is disabled.",
    # current safe posture
    "Dashboard read-only / controlled local route behavior.",
    "Worker OFF.",
    "OpenClaw Not Connected.",
    "Hermes Not Connected.",
    "Google Sheets Disabled.",
    "DISPATCH OFF",
    "WORKER OFF",
    "OPENCLAW NOT CONNECTED",
    "HERMES NOT CONNECTED",
    "GOOGLE SHEETS DISABLED",
    "DISPATCH OFF.",
    "WORKER OFF.",
    "OPENCLAW NOT CONNECTED.",
    "HERMES NOT CONNECTED.",
    "GOOGLE SHEETS DISABLED.",
    "No fixture JSON.",
    "No .json artifact.",
    "No mock data file.",
    "No seed data file.",
    "No fixture directory.",
    "No fixture loader runtime.",
    "No preview data loader.",
    "No local mock data preview runtime.",
    "No Authorization review runtime.",
    "No Artifact creation command runtime.",
    "No Blackboard Loop runtime.",
    "No Dashboard badge display runtime.",
    "No Decision audit display runtime.",
    "No Owner review checklist runtime.",
    "No Dashboard preview display runtime.",
    "No local dry-run preview runtime.",
    "No preview renderer runtime.",
    "No loop contract runtime.",
    "No state machine runtime.",
    "No loop scheduler.",
    "No dispatch gate enabled.",
    "No autonomous execution.",
    "No Hermes activation.",
    "No Hermes blackboard mode.",
    "No Hermes runtime.",
    "No Hermes memory store.",
    "No all-conversation logging.",
    "No cleanup demo task.",
    "No cleanup apply.",
    "No --apply.",
    "No task deletion.",
    "No task archive.",
    "No queue DB change.",
    "No local queue data change.",
    "No Replit queue data change.",
    "No real queue DB read.",
    "No POST.",
    "No live local queue write validation.",
    "No Worker execution.",
    "No OpenClaw call.",
    "No Hermes call.",
    "No Google Sheets read.",
    "No Google Sheets write.",
    "No secrets read.",
    "No secrets copied.",
    "No .env created.",
    "No webhook.",
    "No connector.",
    "No external side effects.",
    "No production DB.",
    "No shared DB.",
    "No remote shared DB.",
    "No Remote Blackboard API runtime.",
    "No Dashboard route created.",
    "No Dashboard endpoint created.",
    "No Dashboard template created.",
    "No Dashboard static asset created.",
    "No app route modified.",
    "No template file modified.",
    "No static file modified.",
    "No Core runtime host.",
    "No Worker runtime.",
    "No OpenClaw runtime.",
    "No systemd service.",
    "No daemon.",
    "No Docker deployment.",
    "No queue synchronization.",
    "No queue migration.",
    "No queue backfill.",
    "No queue merge.",
    "No conflict resolver.",
    "No fixture JSON created.",
    "No mock data file created.",
    "No seed data file created.",
    "No fixture directory created.",
    "No tag.",
    # validation summary
    "v0.8.1-J readiness: ALL PASS.",
    "v0.8.1-I readiness: ALL PASS.",
    "v0.8.1-H readiness: ALL PASS.",
    "v0.8.1-G readiness: ALL PASS.",
    "v0.8.1-F readiness: ALL PASS.",
    "v0.8.1-E readiness: ALL PASS.",
    "v0.8.1-D readiness: ALL PASS.",
    "v0.8.1-C readiness: ALL PASS.",
    "v0.8.1-B readiness: ALL PASS.",
    "v0.8.1-A readiness: ALL PASS.",
    "v0.8.0-G readiness: ALL PASS.",
    "v0.8.0-F readiness: ALL PASS.",
    "v0.8.0-A readiness: ALL PASS.",
    "v0.7.5-A readiness: ALL PASS.",
    "compileall scripts: PASS.",
    # safety grep summary
    "No real unsafe claim was found.",
    "No real secret was found.",
    "Forbidden field names are allowed planning tokens.",
    "Readiness forbidden-pattern matches are benign.",
    # next recommended step
    "v0.8.1-K — Local Mock Data Fixture JSON Artifact Creation Final Authorization Plan",
    "v0.8.1-K must not start unless separately approved by Owner.",
    "v0.8.1-K must not create fixture JSON unless separately approved by Owner.",
    "v0.8.1-K must not create preview data loader.",
    "v0.8.1-K must not modify Dashboard route/template/static.",
    "v0.8.1-K must not read real queue DB.",
    "v0.8.1-K must not send POST.",
    "v0.8.1-K must not start Worker.",
    "v0.8.1-K must not call OpenClaw.",
    "v0.8.1-K must not activate Hermes.",
    "v0.8.1-K must not read or write Google Sheets.",
]
for token in REQUIRED:
    ok(f"doc 含「{token}」") if token in doc else xx(f"doc 含「{token}」")

# ---------------------------------------------------------------------------
# [4] 禁止包含的不安全聲明 / 機密
#     先移除合法的安全否定句（其字面含 forbidden 子字串），再掃 forbidden。
#     forbidden field 名稱（bare token）為 allowed planning token，僅以 value-form
#     pattern 偵測真實機密，故不會誤判。
# ---------------------------------------------------------------------------
print("[4] 禁止包含的不安全聲明 / 機密")
SAFE_NEGATIONS = [
    "No secrets read.",
    "No secrets copied.",
    "No .env created.",
    "No dispatch gate enabled.",
    "Authorization review checklist: no real queue DB read is required.",
    "Authorization rejection review checklist: reject review readiness if real queue DB read is required.",
    "real queue DB read is required.",
    "No real queue DB read.",
    "No fixture JSON created.",
    "No mock data file created.",
    "No seed data file created.",
    "No fixture directory created.",
    "No Google Sheets access is required.",
    "No Google Sheets read.",
    "No Dashboard route created.",
    "No Dashboard endpoint created.",
    "No Dashboard template created.",
    "No Dashboard static asset created.",
    "No app route modified.",
    "No template file modified.",
    "No static file modified.",
]
scrubbed = doc
for phrase in SAFE_NEGATIONS:
    scrubbed = scrubbed.replace(phrase, "")

FORBIDDEN_SUBSTR = [
    "GOOGLE_SHEETS_ENABLED=true",
    "fixture JSON created",
    "fixture directory created",
    "mock data file created",
    "seed data file created",
    "fixture loader runtime created",
    "fixture loader runtime implemented",
    "preview data loader created",
    "preview data loader implemented",
    "local mock data preview runtime created",
    "local mock data preview runtime implemented",
    "Dashboard fixture preview runtime created",
    "Dashboard fixture preview runtime implemented",
    "Authorization review runtime created",
    "Authorization review decision runtime created",
    "Artifact creation command runtime created",
    "Artifact creation planning runtime created",
    "Authorization request runtime created",
    "Authorization decision runtime created",
    "Owner approval request runtime created",
    "Owner approval decision runtime created",
    "Blackboard Loop runtime created",
    "Blackboard Loop runtime implemented",
    "Blackboard Loop runtime enabled",
    "Dashboard badge display runtime created",
    "Dashboard preview display runtime created",
    "Dashboard preview display runtime implemented",
    "Dashboard preview display runtime enabled",
    "preview renderer runtime created",
    "Dashboard route created",
    "Dashboard endpoint created",
    "Dashboard template created",
    "Dashboard static asset created",
    "app route modified",
    "template file modified",
    "static file modified",
    "loop contract runtime created",
    "state machine runtime created",
    "loop scheduler created",
    "loop scheduler enabled",
    "dispatch gate enabled",
    "autonomous execution enabled",
    "Worker enabled",
    "Worker started",
    "Worker runtime created",
    "Worker dispatch enabled",
    "OpenClaw connected",
    "OpenClaw called",
    "OpenClaw runtime created",
    "Hermes connected",
    "Hermes activated",
    "Hermes called",
    "Hermes runtime created",
    "Hermes memory store created",
    "Hermes learning runtime created",
    "Hermes blackboard mode enabled",
    "Google Sheets live write enabled",
    "Google Sheets read",
    "Google Sheets written",
    "Remote Blackboard API runtime created",
    "Remote Blackboard API implemented",
    "Remote Blackboard API read enabled",
    "Remote Blackboard API write enabled",
    "production DB created",
    "shared DB created",
    "remote shared DB created",
    "queue DB read",
    "real queue DB read",
    "queue DB modified",
    "local queue data modified",
    "Replit queue data modified",
    "queue migration performed",
    "queue data synchronized",
    "queue data moved",
    "queue data copied",
    "queue data merged",
    "queue data backfilled",
    "conflict resolver implemented",
    "shared write enabled",
    "Blackboard shared write enabled",
    "POST to Replit Preview was sent",
    "POST to real queue was sent",
    "live queue write validation performed",
    "webhook created",
    "webhook receiver created",
    "connector created",
    "external network call added",
    "API route added",
    "FastAPI router added",
    "database client added",
    "migration added",
    "schema migration performed",
    "source-of-truth switch performed",
    "cleanup applied",
    "demo task cleaned up",
    "tasks deleted",
    "tasks archived",
    "apply_allowed = True",
    "apply_requested = True",
    "dry_run = False",
    "external_side_effects = True",
    "approval_is_execution = True",
    "approval_readiness_is_execution = True",
    "dispatch_enabled = True",
    "artifact_creation_permission = True",
    "loader_permission = True",
    "dashboard_change_permission = True",
    "execution_permission = True",
    "dispatch_permission = True",
    "external_side_effects_permission = True",
    "secrets read",
    "secrets copied",
    "secrets created",
    ".env created",
    "credentials moved",
    "tag created",
]
for token in FORBIDDEN_SUBSTR:
    ok(f"doc 無「{token}」") if token not in scrubbed else xx(f"doc 不得含「{token}」")

# value-bearing secret patterns only (bare forbidden-field tokens are allowed planning tokens)
FORBIDDEN_PATTERNS = [
    (r"spreadsheets/d/[A-Za-z0-9_-]{20,}", "real spreadsheet URL"),
    (r'"?refresh_token"?\s*[:=]\s*"[^"]+"', "refresh token value"),
    (r'"?client_secret"?\s*[:=]\s*"[^"]+"', "client secret value"),
    (r'"?private_key"?\s*[:=]\s*"[^"]+"', "private key value"),
    (r"-----BEGIN[ A-Z]*PRIVATE KEY-----", "private key block"),
    (r'"?spreadsheet_id"?\s*[:=]\s*"[A-Za-z0-9_-]{20,}"', "spreadsheet id value"),
    (r"dashboard_token\s*=\s*[A-Za-z0-9_\-]{8,}", "dashboard token value"),
]
for pat, label in FORBIDDEN_PATTERNS:
    found = bool(re.search(pat, doc, re.IGNORECASE))
    ok(f"doc 無「{label}」") if not found else xx(f"doc 不得含「{label}」")

# ---------------------------------------------------------------------------
# 結果
# ---------------------------------------------------------------------------
total = len(PASS) + len(FAIL)
print(f"\n合計：{len(PASS)}/{total} 通過")
if FAIL:
    print(f"\nXX v0.8.1-J readiness 失敗 {len(FAIL)} 項：")
    for f in FAIL:
        print(f"   - {f}")
    sys.exit(1)
else:
    print(
        "\nv0.8.1-J Local Mock Data Fixture JSON Artifact Creation Authorization Review readiness: ALL PASS"
    )
    sys.exit(0)
