"""v0.8.1-H readiness check: Local Mock Data Fixture JSON Creation Authorization Plan (plan-first / creation-authorization-plan-only).

Creation-authorization-plan verification. Checks that the v0.8.1-H plan document exists and
contains the required sections (1-55), the current-master marker, the v0.8.1-H plan-first /
creation-authorization-plan-only markers, the relationship-to-v0.8.1-G markers, the
problem-statement markers, the Local Mock Data Fixture JSON Creation Authorization Plan definition
markers, the creation authorization planning / artifact prohibition boundary markers, the Owner
approval relationship / candidate artifact relationship / path / filename / schema version reminder
markers, the explicit Owner authorization phrase / non-authorizing phrases markers, the
authorization request shape / required fields markers, the authorization decision fields / decision
values markers, the authorization scope / acceptance / rejection criteria markers, the pre-creation
safety gate / post-authorization no-execution / creation-is-not-execution /
authorization-readiness-is-not-execution / decision-vs-dispatch / artifact creation permission
boundary markers, the future fixture JSON creation / content / loader / Dashboard preview boundary
markers, the Dashboard route / template / static boundary markers, the app / runtime boundary
markers, the queue and real data boundary markers, the Remote Blackboard API relationship markers,
the Worker / OpenClaw / Hermes separation markers, the Google Sheets boundary markers, the secrets
/ privacy / memory boundary markers, the network / webhook / connector boundary markers, the
failure / rollback / audit boundary markers, the authorization / rejection / record / validation
checklist markers, the forbidden fields rejection checklist markers, the boolean safety invariant
checklist markers, the message family authorization checklist markers, the disabled runtime list
markers, the current safe posture markers, the validation summary markers, the safety grep summary
markers, and the next recommended step (v0.8.1-I) — and that it asserts no unsafe "implemented /
created / added / enabled / activated / connected / called / started / written / read / modified /
moved / migrated" claim, no artifact-creation / loader / dashboard-change / execution / dispatch /
external-side-effects permission grant, and contains no real secret value.

The document is allowed to contain safe negations and forbidden-field planning tokens (bare
field names such as refresh_token / client_secret / private_key / spreadsheet_id, listed in the
Forbidden fields rejection checklist). Safe negations that literally embed a forbidden substring
are scrubbed before the forbidden scan; the secret patterns only match value-bearing forms
(name = "value"), so bare planning tokens are not mis-flagged.

This script only reads the plan document. It does NOT read .env, credentials, tokens, or
secrets, makes no network call, imports no app logic (no app.main, no QueueStore), adds no
API route / router / Dashboard route / template / static / database client / migration,
creates no production / shared DB, creates no fixture JSON, no .json artifact, no mock data
file, no seed data file, no fixture directory, no preview data loader, builds no fixture loader
runtime, no Dashboard preview display runtime, reads no real queue DB, writes no queue, sends no
POST, starts no Worker, connects no OpenClaw, activates no Hermes, opens no shared write, and
reads/writes no Google Sheets.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
PASS = []
FAIL = []

DOC_PATH = (
    ROOT
    / "docs"
    / "HERMES_OPENCLAW_LOCAL_MOCK_DATA_FIXTURE_JSON_CREATION_AUTHORIZATION_PLAN_V0_8_1_H.md"
)


def ok(label):
    PASS.append(label)
    print(f"  ok : {label}")


def xx(label):
    FAIL.append(label)
    print(f"  XX : {label}")


# ---------------------------------------------------------------------------
# [1] plan 文件存在
# ---------------------------------------------------------------------------
print("[1] plan 文件存在")
ok("v0.8.1-H plan doc 存在") if DOC_PATH.exists() else xx("v0.8.1-H plan doc 存在")
if not DOC_PATH.exists():
    print("\nXX plan doc 不存在，無法繼續")
    sys.exit(1)

doc = DOC_PATH.read_text(encoding="utf-8")

# ---------------------------------------------------------------------------
# [2] 必須包含的章節（1-55）
# ---------------------------------------------------------------------------
print("[2] 必須包含的章節")
REQUIRED_SECTIONS = [
    "1. Purpose",
    "2. Current master",
    "3. Scope",
    "4. Relationship to v0.8.1-G Local Mock Data Fixture JSON Artifact Owner Approval Plan",
    "5. Problem statement",
    "6. Local Mock Data Fixture JSON Creation Authorization Plan definition",
    "7. Creation authorization planning boundary",
    "8. Fixture JSON artifact prohibition boundary",
    "9. Owner approval relationship",
    "10. Candidate artifact relationship",
    "11. Candidate artifact path reminder",
    "12. Candidate artifact filename reminder",
    "13. Candidate schema version reminder",
    "14. Explicit Owner authorization phrase",
    "15. Non-authorizing phrases",
    "16. Authorization request shape",
    "17. Authorization request required fields",
    "18. Authorization decision fields",
    "19. Authorization decision values",
    "20. Authorization scope",
    "21. Authorization acceptance criteria",
    "22. Authorization rejection criteria",
    "23. Pre-creation safety gate",
    "24. Post-authorization no-execution boundary",
    "25. Creation-is-not-execution boundary",
    "26. Authorization-readiness-is-not-execution boundary",
    "27. Decision-vs-dispatch boundary",
    "28. Artifact creation permission boundary",
    "29. Future fixture JSON creation boundary",
    "30. Future fixture JSON content boundary",
    "31. Future read-only loader boundary",
    "32. Future Dashboard preview boundary",
    "33. Dashboard route / template / static boundary",
    "34. App / runtime boundary",
    "35. Queue and real data boundary",
    "36. Remote Blackboard API relationship",
    "37. Worker / OpenClaw / Hermes separation boundary",
    "38. Google Sheets boundary",
    "39. Secrets / privacy / memory boundary",
    "40. Network / webhook / connector boundary",
    "41. Failure / rollback / audit boundary",
    "42. Authorization checklist",
    "43. Authorization rejection checklist",
    "44. Authorization record checklist",
    "45. Authorization validation checklist",
    "46. Forbidden fields rejection checklist",
    "47. Boolean safety invariant checklist",
    "48. Message family authorization checklist",
    "49. Disabled runtime list",
    "50. Current safe system posture",
    "51. Validation summary",
    "52. Safety grep summary",
    "53. Non-goals",
    "54. Acceptance criteria",
    "55. Next recommended step",
]
for section in REQUIRED_SECTIONS:
    ok(f"doc 含章節「{section}」") if section in doc else xx(f"doc 含章節「{section}」")

# ---------------------------------------------------------------------------
# [3] 必須包含的 markers
# ---------------------------------------------------------------------------
print("[3] 必須包含的 markers")
REQUIRED = [
    # version
    "v0.8.1-H",
    "Local Mock Data Fixture JSON Creation Authorization Plan",
    # current master
    "HEAD = origin/master = eb4a99770780a4c6ce224d6ebdd8115247c44c7b",
    "docs: plan local mock data fixture json artifact owner approval",
    # v0.8.1-H plan-first / creation-authorization-plan-only markers
    "v0.8.1-H Local Mock Data Fixture JSON Creation Authorization Plan is plan-first.",
    "v0.8.1-H Local Mock Data Fixture JSON Creation Authorization Plan is creation-authorization-plan-only.",
    "v0.8.1-H does not create fixture JSON.",
    "v0.8.1-H does not create .json artifact.",
    "v0.8.1-H does not create mock data file.",
    "v0.8.1-H does not create seed data file.",
    "v0.8.1-H does not create fixture directory.",
    "v0.8.1-H does not create preview data loader.",
    "v0.8.1-H does not implement fixture loader runtime.",
    "v0.8.1-H does not implement Dashboard preview display runtime.",
    "v0.8.1-H does not implement local mock data preview runtime.",
    "v0.8.1-H does not create Dashboard route.",
    "v0.8.1-H does not create Dashboard endpoint.",
    "v0.8.1-H does not create Dashboard template.",
    "v0.8.1-H does not create Dashboard static asset.",
    "v0.8.1-H does not modify app.",
    "v0.8.1-H does not modify templates.",
    "v0.8.1-H does not modify static.",
    "v0.8.1-H does not read real queue DB.",
    "v0.8.1-H does not write queue data.",
    "v0.8.1-H does not send POST.",
    "v0.8.1-H does not start Worker.",
    "v0.8.1-H does not connect OpenClaw.",
    "v0.8.1-H does not activate Hermes.",
    "v0.8.1-H does not connect Hermes.",
    "v0.8.1-H does not read Google Sheets.",
    "v0.8.1-H does not write Google Sheets.",
    "v0.8.1-H does not read secrets.",
    "v0.8.1-H does not create .env.",
    "v0.8.1-H does not create webhook.",
    "v0.8.1-H does not create connector.",
    "v0.8.1-H does not create Remote Blackboard API runtime.",
    "v0.8.1-H does not create production DB.",
    "v0.8.1-H does not create shared DB.",
    "v0.8.1-H does not open shared write.",
    # relationship to v0.8.1-G
    "v0.8.1-G Local Mock Data Fixture JSON Artifact Owner Approval Plan is complete.",
    "v0.8.1-H starts the Local Mock Data Fixture JSON Creation Authorization planning step.",
    "v0.8.1-H builds on Local Mock Data Fixture JSON Artifact Owner Approval planning.",
    "v0.8.1-H plans explicit creation authorization before any fixture JSON is created.",
    "v0.8.1-H preserves Owner final approval authority.",
    "v0.8.1-H preserves decision and dispatch separation.",
    "v0.8.1-H preserves audit trail.",
    "v0.8.1-H preserves dispatch-disabled boundary.",
    "v0.8.1-H preserves local mock data preview boundary.",
    "v0.8.1-H preserves the fixture contract boundary.",
    "v0.8.1-H preserves the fixture draft boundary.",
    "v0.8.1-H preserves the fixture JSON approval boundary.",
    "v0.8.1-H preserves the fixture JSON creation boundary.",
    "v0.8.1-H preserves the candidate artifact planning boundary.",
    "v0.8.1-H preserves the artifact owner approval boundary.",
    "v0.8.1-H preserves read-only Dashboard display boundary.",
    "v0.8.1-H does not change any v0.8.1-G boundary.",
    "v0.8.1-H does not change any v0.8.1-F boundary.",
    "v0.8.1-H does not change any v0.8.1-E boundary.",
    "v0.8.1-H does not change any v0.8.1-D boundary.",
    "v0.8.1-H does not change any v0.8.1-C boundary.",
    "v0.8.1-H does not change any v0.8.1-B boundary.",
    "v0.8.1-H does not change any v0.8.1-A boundary.",
    "v0.8.1-H does not change any v0.8.0-G boundary.",
    "v0.8.1-H does not change any v0.8.0-F boundary.",
    # definition
    "Local Mock Data Fixture JSON Creation Authorization Plan means the agreed explicit Owner instruction and final safety gate required before a future fixture JSON artifact is created.",
    "Local Mock Data Fixture JSON Creation Authorization Plan is a planning artifact in v0.8.1-H.",
    "Local Mock Data Fixture JSON Creation Authorization Plan is not runtime code.",
    "Local Mock Data Fixture JSON Creation Authorization Plan is not a fixture JSON file.",
    "Local Mock Data Fixture JSON Creation Authorization Plan is not a mock data file.",
    "Local Mock Data Fixture JSON Creation Authorization Plan is not a preview data loader.",
    "Local Mock Data Fixture JSON Creation Authorization Plan requires separate future plan and Owner approval before artifact creation.",
    # safety principles
    "Approval is not execution.",
    "Approval readiness is not execution permission.",
    "Owner approval is not dispatch permission.",
    "Creation authorization is not execution permission.",
    "Creation authorization readiness is not execution permission.",
    "Creation authorization is not Worker dispatch.",
    "Creation authorization is not OpenClaw call.",
    "Creation authorization is not Hermes action.",
    "Decision and dispatch remain separate.",
    "Fixture JSON creation authorization planning is not fixture JSON creation.",
    "Fixture JSON creation authorization planning is not mock data file creation.",
    "Fixture JSON creation authorization planning is not execution permission.",
    "Fixture JSON creation authorization planning is not Worker dispatch.",
    "Fixture JSON creation authorization planning is not OpenClaw call.",
    "Fixture JSON creation authorization planning is not Hermes action.",
    "Fixture JSON creation authorization planning must not read real queue DB.",
    "Fixture JSON creation authorization planning must not send POST.",
    "Fixture JSON creation authorization planning must not create fixture JSON.",
    "Fixture JSON creation authorization planning must not create preview data loader.",
    "Dashboard preview display is read-only.",
    # creation authorization planning boundary
    "Creation authorization planning boundary is planning only.",
    "Creation authorization planning is expressed as text and pseudo-field descriptions only.",
    "No creation authorization planning runtime is implemented in v0.8.1-H.",
    # artifact prohibition boundary
    "Fixture JSON artifact prohibition boundary is planning only.",
    "No fixture JSON is created in v0.8.1-H.",
    "No .json artifact is created in v0.8.1-H.",
    "No JSON object is created in v0.8.1-H.",
    "Fixture JSON artifact creation requires separate Owner authorization.",
    # Owner approval relationship
    "Owner approval relationship is planning only.",
    "The creation authorization plan builds on the v0.8.1-G Owner approval plan.",
    "The creation authorization plan does not replace Owner approval.",
    "The creation authorization plan does not modify the Owner approval plan.",
    "No Owner approval runtime is implemented in v0.8.1-H.",
    # candidate artifact relationship
    "Candidate artifact relationship is planning only.",
    "The creation authorization plan references the v0.8.1-F candidate artifact plan.",
    "The creation authorization plan does not create the candidate artifact.",
    "The creation authorization plan does not modify the candidate artifact plan.",
    "No candidate artifact runtime is implemented in v0.8.1-H.",
    # candidate artifact path reminder
    "Candidate fixture JSON path: fixtures/local_mock_data/hermes_openclaw_local_mock_messages_v0_8_1.json",
    "Candidate fixture JSON path is planning only.",
    "Candidate fixture JSON path is not created in v0.8.1-H.",
    "Candidate fixture directory is not created in v0.8.1-H.",
    "Candidate fixture JSON file is not created in v0.8.1-H.",
    "Candidate artifact path is inherited from v0.8.1-G planning.",
    # candidate artifact filename reminder
    "Candidate fixture JSON filename: hermes_openclaw_local_mock_messages_v0_8_1.json",
    "Candidate fixture JSON filename is planning only.",
    "Candidate fixture JSON filename is not created in v0.8.1-H.",
    # candidate schema version reminder
    "Candidate fixture JSON schema_version: v0.8.1-local-mock-1.",
    "Candidate schema version is planning only.",
    "Candidate schema version is not implemented in v0.8.1-H.",
    "No schema migration is performed in v0.8.1-H.",
    # explicit Owner authorization phrase
    "Explicit Owner authorization phrase is planning only.",
    "The future explicit Owner authorization phrase may be:",
    "批准建立 v0.8.1 local mock fixture JSON artifact，僅建立 synthetic local-only fixture JSON file，不建立 loader，不改 Dashboard，不讀 real queue DB，不 POST，不啟 Worker/OpenClaw/Hermes/Google Sheets。",
    "This phrase is not issued in v0.8.1-H.",
    "This phrase is not satisfied in v0.8.1-H.",
    "No fixture JSON may be created from v0.8.1-H.",
    # non-authorizing phrases
    "Non-authorizing phrase: approve readiness.",
    "Non-authorizing phrase: approve plan.",
    "Non-authorizing phrase: approve Owner review.",
    "Non-authorizing phrase: approve candidate artifact.",
    "Non-authorizing phrase: approve authorization plan.",
    "Non-authorizing phrase: looks good.",
    "Non-authorizing phrase: proceed to next step.",
    "Non-authorizing phrase: continue.",
    "Non-authorizing phrase: commit this plan.",
    "Non-authorizing phrase: push this plan.",
    "None of these phrases authorize fixture JSON creation.",
    # authorization request shape
    "Authorization request shape is planning only.",
    "Authorization request is not implemented in v0.8.1-H.",
    "Authorization request may include authorization_request_id.",
    "Authorization request may include candidate_artifact_plan_version.",
    "Authorization request may include owner_approval_plan_version.",
    "Authorization request may include candidate_fixture_path.",
    "Authorization request may include candidate_schema_version.",
    "Authorization request may include authorization_scope.",
    "Authorization request may include explicit_authorization_phrase_required.",
    "Authorization request may include requested_artifact_creation_mode.",
    "Authorization request may include synthetic_local_only_confirmation.",
    "Authorization request may include no_loader_confirmation.",
    "Authorization request may include no_dashboard_change_confirmation.",
    "Authorization request may include no_real_queue_db_confirmation.",
    "Authorization request may include no_post_confirmation.",
    "Authorization request may include no_worker_openclaw_hermes_confirmation.",
    "Authorization request may include no_google_sheets_confirmation.",
    "Authorization request may include no_secrets_confirmation.",
    "Authorization request may include rollback_notes_required.",
    "Authorization request may include audit_notes_required.",
    "Authorization request may include created_for.",
    "No Authorization request record is created in v0.8.1-H.",
    # authorization decision fields
    "Authorization decision fields are planning only.",
    "Authorization decision may include authorization_decision_id.",
    "Authorization decision may include authorization_request_id.",
    "Authorization decision may include owner_decision.",
    "Authorization decision may include authorized_scope.",
    "Authorization decision may include rejected_reason.",
    "Authorization decision may include authorization_timestamp.",
    "Authorization decision may include authorization_notes.",
    "Authorization decision may include rollback_notes.",
    "Authorization decision may include artifact_creation_permission.",
    "Authorization decision may include loader_permission.",
    "Authorization decision may include dashboard_change_permission.",
    "Authorization decision may include execution_permission.",
    "Authorization decision may include dispatch_permission.",
    "Authorization decision may include external_side_effects_permission.",
    "No Authorization decision record is created in v0.8.1-H.",
    # decision values
    "Authorization decision value: authorize_synthetic_fixture_json_creation_only.",
    "Authorization decision value: reject_fixture_json_creation_authorization.",
    "Authorization decision value: request_revision.",
    "Authorization decision value: defer_decision.",
    "Authorization decision values are planning only.",
    "No Authorization decision runtime is implemented in v0.8.1-H.",
    # creation-is-not-execution
    "Owner authorization of fixture JSON artifact creation is not execution permission.",
    "Owner authorization of fixture JSON artifact creation is not Worker dispatch permission.",
    "Owner authorization of fixture JSON artifact creation is not OpenClaw call permission.",
    "Owner authorization of fixture JSON artifact creation is not Hermes activation permission.",
    "Owner authorization of fixture JSON artifact creation is not Google Sheets permission.",
    "Owner authorization of fixture JSON artifact creation is not POST permission.",
    "Owner authorization of fixture JSON artifact creation does not authorize a loader.",
    "Owner authorization of fixture JSON artifact creation does not authorize Dashboard changes.",
    "Owner authorization of fixture JSON artifact creation only authorizes a future synthetic local-only artifact creation step if separately scoped.",
    # permission flags false
    "artifact_creation_permission = false",
    "loader_permission = false",
    "dashboard_change_permission = false",
    "execution_permission = false",
    "dispatch_permission = false",
    "external_side_effects_permission = false",
    # authorization request field candidates (bare tokens)
    "authorization_request_id",
    "candidate_artifact_plan_version",
    "owner_approval_plan_version",
    "candidate_fixture_path",
    "candidate_schema_version",
    "authorization_scope",
    "explicit_authorization_phrase_required",
    "requested_artifact_creation_mode",
    "synthetic_local_only_confirmation",
    "no_loader_confirmation",
    "no_dashboard_change_confirmation",
    "no_real_queue_db_confirmation",
    "no_post_confirmation",
    "no_worker_openclaw_hermes_confirmation",
    "no_google_sheets_confirmation",
    "no_secrets_confirmation",
    "rollback_notes_required",
    "audit_notes_required",
    "created_for",
    # authorization decision field candidates (bare tokens)
    "authorization_decision_id",
    "owner_decision",
    "authorized_scope",
    "rejected_reason",
    "authorization_timestamp",
    "authorization_notes",
    "rollback_notes",
    # forbidden field candidates (bare tokens — allowed planning tokens)
    "real_queue_id",
    "real_task_id",
    "real_user_secret",
    "spreadsheet_id",
    "refresh_token",
    "client_secret",
    "private_key",
    "webhook_url",
    "openclaw_endpoint",
    "hermes_endpoint",
    "production_db_url",
    "remote_blackboard_api_url",
    # boolean safety invariants
    "is_mock = true",
    "dispatch_enabled = false",
    "worker_running = false",
    "openclaw_connected = false",
    "hermes_connected = false",
    "google_sheets_enabled = false",
    "external_side_effects = false",
    "approval_is_execution = false",
    "approval_readiness_is_execution = false",
    "Boolean safety invariant checklist is planning only.",
    "No boolean safety invariant runtime is implemented in v0.8.1-H.",
    # message families
    "Mock Task Message",
    "Mock Decision Message",
    "Mock Result Message",
    "Mock Advice Message",
    "Mock Badge Status",
    "Mock Runtime-off Status",
    # authorization checklist
    "Authorization checklist: candidate artifact path is reviewed.",
    "Authorization checklist: candidate schema_version is reviewed.",
    "Authorization checklist: candidate artifact plan is reviewed.",
    "Authorization checklist: Owner approval plan is reviewed.",
    "Authorization checklist: explicit authorization phrase is reviewed.",
    "Authorization checklist: non-authorizing phrases are reviewed.",
    "Authorization checklist: authorization request shape is reviewed.",
    "Authorization checklist: authorization decision fields are reviewed.",
    "Authorization checklist: authorization scope is reviewed.",
    "Authorization checklist: pre-creation safety gate is reviewed.",
    "Authorization checklist: creation-is-not-execution boundary is reviewed.",
    "Authorization checklist: decision-vs-dispatch boundary is reviewed.",
    "Authorization checklist: future artifact creation boundary is reviewed.",
    "Authorization checklist: no loader is authorized.",
    "Authorization checklist: no Dashboard change is authorized.",
    "Authorization checklist: no real queue DB read is required.",
    "Authorization checklist: no POST is required.",
    "Authorization checklist: no Worker/OpenClaw/Hermes action is required.",
    "Authorization checklist: no Google Sheets access is required.",
    "Authorization checklist: no secrets access is required.",
    # authorization rejection checklist
    "Authorization rejection checklist: reject authorization if explicit authorization phrase is missing.",
    "Authorization rejection checklist: reject authorization if candidate artifact path is unclear.",
    "Authorization rejection checklist: reject authorization if schema_version is unclear.",
    "Authorization rejection checklist: reject authorization if authorization scope is unclear.",
    "Authorization rejection checklist: reject authorization if artifact creation mode is unclear.",
    "Authorization rejection checklist: reject authorization if synthetic local-only confirmation is missing.",
    "Authorization rejection checklist: reject authorization if no-loader confirmation is missing.",
    "Authorization rejection checklist: reject authorization if no-Dashboard-change confirmation is missing.",
    "Authorization rejection checklist: reject authorization if rollback notes are missing.",
    "Authorization rejection checklist: reject authorization if audit notes are missing.",
    "Authorization rejection checklist: reject authorization if loader permission is requested.",
    "Authorization rejection checklist: reject authorization if Dashboard change permission is requested.",
    "Authorization rejection checklist: reject authorization if execution permission is requested.",
    "Authorization rejection checklist: reject authorization if dispatch permission is requested.",
    "Authorization rejection checklist: reject authorization if external side effects are requested.",
    "Authorization rejection checklist: reject authorization if real queue DB read is required.",
    "Authorization rejection checklist: reject authorization if POST is required.",
    "Authorization rejection checklist: reject authorization if Worker/OpenClaw/Hermes action is required.",
    "Authorization rejection checklist: reject authorization if Google Sheets access is required.",
    "Authorization rejection checklist: reject authorization if secrets access is required.",
    # authorization record checklist
    "Authorization record checklist: authorization request must remain synthetic local-only.",
    "Authorization record checklist: authorization decision must remain synthetic local-only.",
    "Authorization record checklist: authorization request must not contain forbidden fields.",
    "Authorization record checklist: authorization decision must not contain forbidden fields.",
    "Authorization record checklist: authorization record must not contain real queue IDs.",
    "Authorization record checklist: authorization record must not contain real task IDs.",
    "Authorization record checklist: authorization record must not contain real user data.",
    "Authorization record checklist: authorization record must not contain spreadsheet IDs.",
    "Authorization record checklist: authorization record must not contain tokens.",
    "Authorization record checklist: authorization record must not contain secrets.",
    "Authorization record checklist: authorization record must not contain endpoints.",
    "Authorization record checklist: authorization record must preserve artifact_creation_permission = false in v0.8.1-H.",
    "Authorization record checklist: authorization record must preserve loader_permission = false.",
    "Authorization record checklist: authorization record must preserve dashboard_change_permission = false.",
    "Authorization record checklist: authorization record must preserve execution_permission = false.",
    "Authorization record checklist: authorization record must preserve dispatch_permission = false.",
    "Authorization record checklist: authorization record must preserve external_side_effects_permission = false.",
    # validation checklist
    "Validation checklist: creation authorization plan must remain synthetic local-only.",
    "Validation checklist: creation authorization plan must contain no fixture JSON.",
    "Validation checklist: creation authorization plan must contain no JSON object.",
    "Validation checklist: creation authorization plan must contain no mock data file.",
    "Validation checklist: creation authorization plan must contain no fixture directory.",
    "Validation checklist: creation authorization plan must contain no preview data loader.",
    "Validation checklist: creation authorization plan must contain no runtime.",
    "Validation checklist: creation authorization plan must contain no forbidden field values.",
    "Validation checklist: creation authorization plan must satisfy boolean safety invariants.",
    "Validation checklist: creation authorization plan must keep artifact_creation_permission = false.",
    "Validation checklist: creation authorization plan must keep loader_permission = false.",
    "Validation checklist: creation authorization plan must keep dashboard_change_permission = false.",
    "Validation checklist: creation authorization plan must not enable dispatch.",
    "Validation checklist: creation authorization plan must not enable Worker.",
    "Validation checklist: creation authorization plan must not connect OpenClaw.",
    "Validation checklist: creation authorization plan must not activate Hermes.",
    "Validation checklist: creation authorization plan must not enable Google Sheets.",
    "Validation checklist: creation authorization plan must not read real queue DB.",
    "Validation checklist: creation authorization plan must not send POST.",
    "Validation checklist: creation authorization plan must not read secrets.",
    # forbidden field rejection checklist
    "Forbidden field rejection checklist: reject if real_queue_id appears as a field.",
    "Forbidden field rejection checklist: reject if real_task_id appears as a field.",
    "Forbidden field rejection checklist: reject if real_user_secret appears as a field.",
    "Forbidden field rejection checklist: reject if spreadsheet_id appears as a field.",
    "Forbidden field rejection checklist: reject if refresh_token appears as a field.",
    "Forbidden field rejection checklist: reject if client_secret appears as a field.",
    "Forbidden field rejection checklist: reject if private_key appears as a field.",
    "Forbidden field rejection checklist: reject if webhook_url appears as a field.",
    "Forbidden field rejection checklist: reject if openclaw_endpoint appears as a field.",
    "Forbidden field rejection checklist: reject if hermes_endpoint appears as a field.",
    "Forbidden field rejection checklist: reject if production_db_url appears as a field.",
    "Forbidden field rejection checklist: reject if remote_blackboard_api_url appears as a field.",
    # separation
    "Worker remains OFF.",
    "OpenClaw remains Not Connected.",
    "Hermes remains Not Connected.",
    "Worker is dispatch runtime.",
    "OpenClaw is execution / gateway / tools layer.",
    "Hermes is strategy / proxy / memory layer.",
    "Worker must not run from plan-only fixture JSON creation authorization planning.",
    "OpenClaw must not execute from plan-only fixture JSON creation authorization planning.",
    "Hermes must not act from plan-only fixture JSON creation authorization planning.",
    # Google Sheets boundary
    "Google Sheets remains Disabled.",
    "No Google Sheets read is required.",
    "No Google Sheets write is performed.",
    "No Google Sheets live write is enabled.",
    # secrets / privacy / memory boundary
    "No secrets are read.",
    "No secrets are copied.",
    "No secrets are created.",
    "No .env file is created.",
    "No credentials are moved.",
    "No production secrets are copied.",
    "No Hermes memory store is created.",
    "No Hermes learning runtime is created.",
    "No private conversation log is created.",
    "No all-conversation logging is enabled.",
    # network / webhook / connector boundary
    "No webhook is created.",
    "No webhook receiver is created.",
    "No connector is created.",
    "No external network call is added.",
    "No inbound listener is added.",
    "No outbound integration is added.",
    "No port exposure is configured.",
    "No POST is sent.",
    "No live queue write validation is performed.",
    # disabled runtime list
    "Fixture JSON creation authorization planning runtime is disabled.",
    "Authorization request runtime is disabled.",
    "Authorization decision runtime is disabled.",
    "Owner approval request runtime is disabled.",
    "Owner approval decision runtime is disabled.",
    "Fixture loader runtime is disabled.",
    "Preview data loader runtime is disabled.",
    "Local mock data preview runtime is disabled.",
    "Dashboard fixture preview runtime is disabled.",
    "Blackboard Loop runtime is disabled.",
    "Dashboard badge display runtime is disabled.",
    "Decision audit display runtime is disabled.",
    "Owner review checklist runtime is disabled.",
    "Dashboard preview display runtime is disabled.",
    "Dispatch gate is disabled.",
    "Worker runtime is disabled.",
    "OpenClaw runtime is disabled.",
    "Hermes runtime is disabled.",
    "Remote Blackboard API runtime is disabled.",
    "Shared write is disabled.",
    "Google Sheets write is disabled.",
    "Autonomous execution is disabled.",
    # current safe posture
    "Dashboard read-only / controlled local route behavior.",
    "Worker OFF.",
    "OpenClaw Not Connected.",
    "Hermes Not Connected.",
    "Google Sheets Disabled.",
    "DISPATCH OFF.",
    "WORKER OFF.",
    "OPENCLAW NOT CONNECTED.",
    "HERMES NOT CONNECTED.",
    "GOOGLE SHEETS DISABLED.",
    "No fixture JSON.",
    "No .json artifact.",
    "No mock data file.",
    "No seed data file.",
    "No fixture directory.",
    "No fixture loader runtime.",
    "No preview data loader.",
    "No local mock data preview runtime.",
    "No Authorization request runtime.",
    "No Authorization decision runtime.",
    "No Owner approval request runtime.",
    "No Owner approval decision runtime.",
    "No Blackboard Loop runtime.",
    "No Dashboard badge display runtime.",
    "No Decision audit display runtime.",
    "No Owner review checklist runtime.",
    "No Dashboard preview display runtime.",
    "No local dry-run preview runtime.",
    "No preview renderer runtime.",
    "No loop contract runtime.",
    "No state machine runtime.",
    "No loop scheduler.",
    "No dispatch gate enabled.",
    "No autonomous execution.",
    "No Hermes activation.",
    "No Hermes blackboard mode.",
    "No Hermes runtime.",
    "No Hermes memory store.",
    "No all-conversation logging.",
    "No cleanup demo task.",
    "No cleanup apply.",
    "No --apply.",
    "No task deletion.",
    "No task archive.",
    "No queue DB change.",
    "No local queue data change.",
    "No Replit queue data change.",
    "No real queue DB read.",
    "No POST.",
    "No live local queue write validation.",
    "No Worker execution.",
    "No OpenClaw call.",
    "No Hermes call.",
    "No Google Sheets read.",
    "No Google Sheets write.",
    "No secrets read.",
    "No secrets copied.",
    "No .env created.",
    "No webhook.",
    "No connector.",
    "No external side effects.",
    "No production DB.",
    "No shared DB.",
    "No remote shared DB.",
    "No Remote Blackboard API runtime.",
    "No Dashboard route created.",
    "No Dashboard endpoint created.",
    "No Dashboard template created.",
    "No Dashboard static asset created.",
    "No app route modified.",
    "No template file modified.",
    "No static file modified.",
    "No Core runtime host.",
    "No Worker runtime.",
    "No OpenClaw runtime.",
    "No systemd service.",
    "No daemon.",
    "No Docker deployment.",
    "No queue synchronization.",
    "No queue migration.",
    "No queue backfill.",
    "No queue merge.",
    "No conflict resolver.",
    "No fixture JSON created.",
    "No mock data file created.",
    "No seed data file created.",
    "No fixture directory created.",
    "No tag.",
    # validation summary
    "v0.8.1-H readiness: ALL PASS.",
    "v0.8.1-G readiness: ALL PASS.",
    "v0.8.1-F readiness: ALL PASS.",
    "v0.8.1-E readiness: ALL PASS.",
    "v0.8.1-D readiness: ALL PASS.",
    "v0.8.1-C readiness: ALL PASS.",
    "v0.8.1-B readiness: ALL PASS.",
    "v0.8.1-A readiness: ALL PASS.",
    "v0.8.0-G readiness: ALL PASS.",
    "v0.8.0-F readiness: ALL PASS.",
    "v0.8.0-A readiness: ALL PASS.",
    "v0.7.5-A readiness: ALL PASS.",
    "compileall scripts: PASS.",
    # safety grep summary
    "No real unsafe claim was found.",
    "No real secret was found.",
    "Forbidden field names are allowed planning tokens.",
    "Readiness forbidden-pattern matches are benign.",
    # next recommended step
    "v0.8.1-I — Local Mock Data Fixture JSON Artifact Creation Plan",
    "v0.8.1-I must not start unless separately approved by Owner.",
    "v0.8.1-I must not create fixture JSON unless separately approved by Owner.",
    "v0.8.1-I must not create preview data loader.",
    "v0.8.1-I must not modify Dashboard route/template/static.",
    "v0.8.1-I must not read real queue DB.",
    "v0.8.1-I must not send POST.",
    "v0.8.1-I must not start Worker.",
    "v0.8.1-I must not call OpenClaw.",
    "v0.8.1-I must not activate Hermes.",
    "v0.8.1-I must not read or write Google Sheets.",
]
for token in REQUIRED:
    ok(f"doc 含「{token}」") if token in doc else xx(f"doc 含「{token}」")

# ---------------------------------------------------------------------------
# [4] 禁止包含的不安全聲明 / 機密
#     先移除合法的安全否定句（其字面含 forbidden 子字串），再掃 forbidden。
#     forbidden field 名稱（bare token）為 allowed planning token，僅以 value-form
#     pattern 偵測真實機密，故不會誤判。
# ---------------------------------------------------------------------------
print("[4] 禁止包含的不安全聲明 / 機密")
SAFE_NEGATIONS = [
    "No secrets read.",
    "No secrets copied.",
    "No .env created.",
    "No dispatch gate enabled.",
    "Authorization checklist: no real queue DB read is required.",
    "Authorization rejection checklist: reject authorization if real queue DB read is required.",
    "Authorization scope: does not authorize real queue DB read.",
    "Rejection criteria: real queue DB read, POST, Worker, OpenClaw, Hermes, Google Sheets, or secrets access is required.",
    "real queue DB read is required.",
    "No real queue DB read.",
    "No fixture JSON created.",
    "No mock data file created.",
    "No seed data file created.",
    "No fixture directory created.",
    "No Google Sheets read is required.",
    "No Google Sheets read.",
    "No Dashboard route created.",
    "No Dashboard endpoint created.",
    "No Dashboard template created.",
    "No Dashboard static asset created.",
    "No app route modified.",
    "No template file modified.",
    "No static file modified.",
]
scrubbed = doc
for phrase in SAFE_NEGATIONS:
    scrubbed = scrubbed.replace(phrase, "")

FORBIDDEN_SUBSTR = [
    "GOOGLE_SHEETS_ENABLED=true",
    "fixture JSON created",
    "fixture directory created",
    "mock data file created",
    "seed data file created",
    "fixture loader runtime created",
    "fixture loader runtime implemented",
    "preview data loader created",
    "preview data loader implemented",
    "local mock data preview runtime created",
    "local mock data preview runtime implemented",
    "Dashboard fixture preview runtime created",
    "Dashboard fixture preview runtime implemented",
    "Authorization request runtime created",
    "Authorization decision runtime created",
    "Owner approval request runtime created",
    "Owner approval decision runtime created",
    "Blackboard Loop runtime created",
    "Blackboard Loop runtime implemented",
    "Blackboard Loop runtime enabled",
    "Dashboard badge display runtime created",
    "Dashboard preview display runtime created",
    "Dashboard preview display runtime implemented",
    "Dashboard preview display runtime enabled",
    "preview renderer runtime created",
    "Dashboard route created",
    "Dashboard endpoint created",
    "Dashboard template created",
    "Dashboard static asset created",
    "app route modified",
    "template file modified",
    "static file modified",
    "loop contract runtime created",
    "state machine runtime created",
    "loop scheduler created",
    "loop scheduler enabled",
    "dispatch gate enabled",
    "autonomous execution enabled",
    "Worker enabled",
    "Worker started",
    "Worker runtime created",
    "Worker dispatch enabled",
    "OpenClaw connected",
    "OpenClaw called",
    "OpenClaw runtime created",
    "Hermes connected",
    "Hermes activated",
    "Hermes called",
    "Hermes runtime created",
    "Hermes memory store created",
    "Hermes learning runtime created",
    "Hermes blackboard mode enabled",
    "Google Sheets live write enabled",
    "Google Sheets read",
    "Google Sheets written",
    "Remote Blackboard API runtime created",
    "Remote Blackboard API implemented",
    "Remote Blackboard API read enabled",
    "Remote Blackboard API write enabled",
    "production DB created",
    "shared DB created",
    "remote shared DB created",
    "queue DB read",
    "real queue DB read",
    "queue DB modified",
    "local queue data modified",
    "Replit queue data modified",
    "queue migration performed",
    "queue data synchronized",
    "queue data moved",
    "queue data copied",
    "queue data merged",
    "queue data backfilled",
    "conflict resolver implemented",
    "shared write enabled",
    "Blackboard shared write enabled",
    "POST to Replit Preview was sent",
    "POST to real queue was sent",
    "live queue write validation performed",
    "webhook created",
    "webhook receiver created",
    "connector created",
    "external network call added",
    "API route added",
    "FastAPI router added",
    "database client added",
    "migration added",
    "schema migration performed",
    "source-of-truth switch performed",
    "cleanup applied",
    "demo task cleaned up",
    "tasks deleted",
    "tasks archived",
    "apply_allowed = True",
    "apply_requested = True",
    "dry_run = False",
    "external_side_effects = True",
    "approval_is_execution = True",
    "approval_readiness_is_execution = True",
    "dispatch_enabled = True",
    "artifact_creation_permission = True",
    "loader_permission = True",
    "dashboard_change_permission = True",
    "execution_permission = True",
    "dispatch_permission = True",
    "external_side_effects_permission = True",
    "secrets read",
    "secrets copied",
    "secrets created",
    ".env created",
    "credentials moved",
    "tag created",
]
for token in FORBIDDEN_SUBSTR:
    ok(f"doc 無「{token}」") if token not in scrubbed else xx(f"doc 不得含「{token}」")

# value-bearing secret patterns only (bare forbidden-field tokens are allowed planning tokens)
FORBIDDEN_PATTERNS = [
    (r"spreadsheets/d/[A-Za-z0-9_-]{20,}", "real spreadsheet URL"),
    (r'"?refresh_token"?\s*[:=]\s*"[^"]+"', "refresh token value"),
    (r'"?client_secret"?\s*[:=]\s*"[^"]+"', "client secret value"),
    (r'"?private_key"?\s*[:=]\s*"[^"]+"', "private key value"),
    (r"-----BEGIN[ A-Z]*PRIVATE KEY-----", "private key block"),
    (r'"?spreadsheet_id"?\s*[:=]\s*"[A-Za-z0-9_-]{20,}"', "spreadsheet id value"),
    (r"dashboard_token\s*=\s*[A-Za-z0-9_\-]{8,}", "dashboard token value"),
]
for pat, label in FORBIDDEN_PATTERNS:
    found = bool(re.search(pat, doc, re.IGNORECASE))
    ok(f"doc 無「{label}」") if not found else xx(f"doc 不得含「{label}」")

# ---------------------------------------------------------------------------
# 結果
# ---------------------------------------------------------------------------
total = len(PASS) + len(FAIL)
print(f"\n合計：{len(PASS)}/{total} 通過")
if FAIL:
    print(f"\nXX v0.8.1-H readiness 失敗 {len(FAIL)} 項：")
    for f in FAIL:
        print(f"   - {f}")
    sys.exit(1)
else:
    print(
        "\nv0.8.1-H Local Mock Data Fixture JSON Creation Authorization Plan readiness: ALL PASS"
    )
    sys.exit(0)
