"""v0.8.1-I readiness check: Local Mock Data Fixture JSON Artifact Creation Plan (plan-first / artifact-creation-plan-only).

Artifact-creation-plan verification. Checks that the v0.8.1-I plan document exists and contains
the required sections (1-62), the current-master marker, the v0.8.1-I plan-first /
artifact-creation-plan-only markers, the relationship-to-v0.8.1-H markers, the problem-statement
markers, the Local Mock Data Fixture JSON Artifact Creation Plan definition markers, the artifact
creation planning / artifact prohibition boundary markers, the creation authorization / explicit
Owner authorization phrase relationship markers, the candidate artifact path / filename / schema
version markers, the candidate top-level shape / records collection / record count / ordering
blueprint markers, the synthetic local-only value policy / no-real-data policy markers, the
required fields / forbidden fields / boolean safety invariant blueprint markers, the message family
blueprint markers, the per-family record blueprint markers (Mock Task / Decision / Result / Advice
Message, Mock Badge Status, Mock Runtime-off Status), the display copy / safety_notes /
next_owner_action / audit_notes / rollback_notes blueprint markers, the future artifact creation
command / validation / rollback / read-only loader / Dashboard preview boundary markers, the
Dashboard route / template / static boundary markers, the app / runtime boundary markers, the
queue and real data boundary markers, the Remote Blackboard API relationship markers, the Worker /
OpenClaw / Hermes separation markers, the Google Sheets boundary markers, the secrets / privacy /
memory boundary markers, the network / webhook / connector boundary markers, the failure /
rollback / audit boundary markers, the artifact creation / rejection / validation / rollback
checklist markers, the forbidden fields rejection checklist markers, the boolean safety invariant
checklist markers, the message family creation checklist markers, the disabled runtime list
markers, the current safe posture markers, the validation summary markers, the safety grep summary
markers, and the next recommended step (v0.8.1-J) — and that it asserts no unsafe "implemented /
created / added / enabled / activated / connected / called / started / written / read / modified /
moved / migrated" claim, no artifact-creation / loader / dashboard-change / execution / dispatch /
external-side-effects permission grant, and contains no real secret value.

The document is allowed to contain safe negations and forbidden-field planning tokens (bare
field names such as refresh_token / client_secret / private_key / spreadsheet_id, listed in the
Forbidden fields rejection checklist). Safe negations that literally embed a forbidden substring
are scrubbed before the forbidden scan; the secret patterns only match value-bearing forms
(name = "value"), so bare planning tokens are not mis-flagged.

This script only reads the plan document. It does NOT read .env, credentials, tokens, or
secrets, makes no network call, imports no app logic (no app.main, no QueueStore), adds no
API route / router / Dashboard route / template / static / database client / migration,
creates no production / shared DB, creates no fixture JSON, no .json artifact, no mock data
file, no seed data file, no fixture directory, no preview data loader, builds no fixture loader
runtime, no Dashboard preview display runtime, reads no real queue DB, writes no queue, sends no
POST, starts no Worker, connects no OpenClaw, activates no Hermes, opens no shared write, and
reads/writes no Google Sheets.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
PASS = []
FAIL = []

DOC_PATH = (
    ROOT
    / "docs"
    / "HERMES_OPENCLAW_LOCAL_MOCK_DATA_FIXTURE_JSON_ARTIFACT_CREATION_PLAN_V0_8_1_I.md"
)


def ok(label):
    PASS.append(label)
    print(f"  ok : {label}")


def xx(label):
    FAIL.append(label)
    print(f"  XX : {label}")


# ---------------------------------------------------------------------------
# [1] plan 文件存在
# ---------------------------------------------------------------------------
print("[1] plan 文件存在")
ok("v0.8.1-I plan doc 存在") if DOC_PATH.exists() else xx("v0.8.1-I plan doc 存在")
if not DOC_PATH.exists():
    print("\nXX plan doc 不存在，無法繼續")
    sys.exit(1)

doc = DOC_PATH.read_text(encoding="utf-8")

# ---------------------------------------------------------------------------
# [2] 必須包含的章節（1-62）
# ---------------------------------------------------------------------------
print("[2] 必須包含的章節")
REQUIRED_SECTIONS = [
    "1. Purpose",
    "2. Current master",
    "3. Scope",
    "4. Relationship to v0.8.1-H Local Mock Data Fixture JSON Creation Authorization Plan",
    "5. Problem statement",
    "6. Local Mock Data Fixture JSON Artifact Creation Plan definition",
    "7. Artifact creation planning boundary",
    "8. Fixture JSON artifact prohibition boundary",
    "9. Creation authorization relationship",
    "10. Explicit Owner authorization phrase relationship",
    "11. Candidate artifact path",
    "12. Candidate artifact filename",
    "13. Candidate schema version",
    "14. Candidate top-level shape blueprint",
    "15. Candidate records collection blueprint",
    "16. Candidate record count blueprint",
    "17. Candidate record ordering blueprint",
    "18. Synthetic local-only value policy",
    "19. No-real-data policy",
    "20. Required fields blueprint",
    "21. Forbidden fields rejection blueprint",
    "22. Boolean safety invariant blueprint",
    "23. Message family blueprint",
    "24. Mock Task Message record blueprint",
    "25. Mock Decision Message record blueprint",
    "26. Mock Result Message record blueprint",
    "27. Mock Advice Message record blueprint",
    "28. Mock Badge Status record blueprint",
    "29. Mock Runtime-off Status record blueprint",
    "30. Candidate display copy blueprint",
    "31. Candidate safety_notes blueprint",
    "32. Candidate next_owner_action blueprint",
    "33. Candidate audit_notes blueprint",
    "34. Candidate rollback_notes blueprint",
    "35. Future artifact creation command boundary",
    "36. Future artifact validation boundary",
    "37. Future artifact rollback boundary",
    "38. Future read-only loader boundary",
    "39. Future Dashboard preview boundary",
    "40. Dashboard route / template / static boundary",
    "41. App / runtime boundary",
    "42. Queue and real data boundary",
    "43. Remote Blackboard API relationship",
    "44. Worker / OpenClaw / Hermes separation boundary",
    "45. Google Sheets boundary",
    "46. Secrets / privacy / memory boundary",
    "47. Network / webhook / connector boundary",
    "48. Failure / rollback / audit boundary",
    "49. Artifact creation checklist",
    "50. Artifact rejection checklist",
    "51. Artifact validation checklist",
    "52. Artifact rollback checklist",
    "53. Forbidden fields rejection checklist",
    "54. Boolean safety invariant checklist",
    "55. Message family creation checklist",
    "56. Disabled runtime list",
    "57. Current safe system posture",
    "58. Validation summary",
    "59. Safety grep summary",
    "60. Non-goals",
    "61. Acceptance criteria",
    "62. Next recommended step",
]
for section in REQUIRED_SECTIONS:
    ok(f"doc 含章節「{section}」") if section in doc else xx(f"doc 含章節「{section}」")

# ---------------------------------------------------------------------------
# [3] 必須包含的 markers
# ---------------------------------------------------------------------------
print("[3] 必須包含的 markers")
REQUIRED = [
    # version
    "v0.8.1-I",
    "Local Mock Data Fixture JSON Artifact Creation Plan",
    # current master
    "HEAD = origin/master = 5699198d659ae0ce62f2ebd620a3a7238e80b2a3",
    "docs: plan local mock data fixture json creation authorization",
    # v0.8.1-I plan-first / artifact-creation-plan-only markers
    "v0.8.1-I Local Mock Data Fixture JSON Artifact Creation Plan is plan-first.",
    "v0.8.1-I Local Mock Data Fixture JSON Artifact Creation Plan is artifact-creation-plan-only.",
    "v0.8.1-I does not create fixture JSON.",
    "v0.8.1-I does not create .json artifact.",
    "v0.8.1-I does not create mock data file.",
    "v0.8.1-I does not create seed data file.",
    "v0.8.1-I does not create fixture directory.",
    "v0.8.1-I does not create preview data loader.",
    "v0.8.1-I does not implement fixture loader runtime.",
    "v0.8.1-I does not implement Dashboard preview display runtime.",
    "v0.8.1-I does not implement local mock data preview runtime.",
    "v0.8.1-I does not create Dashboard route.",
    "v0.8.1-I does not create Dashboard endpoint.",
    "v0.8.1-I does not create Dashboard template.",
    "v0.8.1-I does not create Dashboard static asset.",
    "v0.8.1-I does not modify app.",
    "v0.8.1-I does not modify templates.",
    "v0.8.1-I does not modify static.",
    "v0.8.1-I does not read real queue DB.",
    "v0.8.1-I does not write queue data.",
    "v0.8.1-I does not send POST.",
    "v0.8.1-I does not start Worker.",
    "v0.8.1-I does not connect OpenClaw.",
    "v0.8.1-I does not activate Hermes.",
    "v0.8.1-I does not connect Hermes.",
    "v0.8.1-I does not read Google Sheets.",
    "v0.8.1-I does not write Google Sheets.",
    "v0.8.1-I does not read secrets.",
    "v0.8.1-I does not create .env.",
    "v0.8.1-I does not create webhook.",
    "v0.8.1-I does not create connector.",
    "v0.8.1-I does not create Remote Blackboard API runtime.",
    "v0.8.1-I does not create production DB.",
    "v0.8.1-I does not create shared DB.",
    "v0.8.1-I does not open shared write.",
    # relationship to v0.8.1-H
    "v0.8.1-H Local Mock Data Fixture JSON Creation Authorization Plan is complete.",
    "v0.8.1-I starts the Local Mock Data Fixture JSON Artifact Creation planning step.",
    "v0.8.1-I builds on Local Mock Data Fixture JSON Creation Authorization planning.",
    "v0.8.1-I plans artifact creation before any fixture JSON is created.",
    "v0.8.1-I preserves Owner final approval authority.",
    "v0.8.1-I preserves decision and dispatch separation.",
    "v0.8.1-I preserves audit trail.",
    "v0.8.1-I preserves dispatch-disabled boundary.",
    "v0.8.1-I preserves local mock data preview boundary.",
    "v0.8.1-I preserves the fixture contract boundary.",
    "v0.8.1-I preserves the fixture draft boundary.",
    "v0.8.1-I preserves the fixture JSON approval boundary.",
    "v0.8.1-I preserves the fixture JSON creation boundary.",
    "v0.8.1-I preserves the candidate artifact planning boundary.",
    "v0.8.1-I preserves the artifact owner approval boundary.",
    "v0.8.1-I preserves the creation authorization boundary.",
    "v0.8.1-I preserves read-only Dashboard display boundary.",
    "v0.8.1-I does not change any v0.8.1-H boundary.",
    "v0.8.1-I does not change any v0.8.1-G boundary.",
    "v0.8.1-I does not change any v0.8.1-F boundary.",
    "v0.8.1-I does not change any v0.8.1-E boundary.",
    "v0.8.1-I does not change any v0.8.1-D boundary.",
    "v0.8.1-I does not change any v0.8.1-C boundary.",
    "v0.8.1-I does not change any v0.8.1-B boundary.",
    "v0.8.1-I does not change any v0.8.1-A boundary.",
    "v0.8.1-I does not change any v0.8.0-G boundary.",
    "v0.8.1-I does not change any v0.8.0-F boundary.",
    # definition
    "Local Mock Data Fixture JSON Artifact Creation Plan means the agreed blueprint a future fixture JSON artifact must follow when it is created.",
    "Local Mock Data Fixture JSON Artifact Creation Plan is a planning artifact in v0.8.1-I.",
    "Local Mock Data Fixture JSON Artifact Creation Plan is not runtime code.",
    "Local Mock Data Fixture JSON Artifact Creation Plan is not a fixture JSON file.",
    "Local Mock Data Fixture JSON Artifact Creation Plan is not a mock data file.",
    "Local Mock Data Fixture JSON Artifact Creation Plan is not a preview data loader.",
    "Local Mock Data Fixture JSON Artifact Creation Plan requires separate future plan and Owner approval before artifact creation.",
    # safety principles
    "Approval is not execution.",
    "Approval readiness is not execution permission.",
    "Owner approval is not dispatch permission.",
    "Creation authorization is not execution permission.",
    "Artifact creation planning is not artifact creation.",
    "Artifact creation planning is not fixture JSON creation.",
    "Artifact creation planning is not mock data file creation.",
    "Artifact creation planning is not execution permission.",
    "Artifact creation planning is not Worker dispatch.",
    "Artifact creation planning is not OpenClaw call.",
    "Artifact creation planning is not Hermes action.",
    "Artifact creation planning must not read real queue DB.",
    "Artifact creation planning must not send POST.",
    "Artifact creation planning must not create fixture JSON.",
    "Artifact creation planning must not create preview data loader.",
    "Decision and dispatch remain separate.",
    "Dashboard preview display is read-only.",
    # artifact creation planning boundary
    "Artifact creation planning boundary is planning only.",
    "Artifact creation planning is expressed as text and pseudo-field descriptions only.",
    "No artifact creation planning runtime is implemented in v0.8.1-I.",
    # artifact prohibition boundary
    "Fixture JSON artifact prohibition boundary is planning only.",
    "No fixture JSON is created in v0.8.1-I.",
    "No .json artifact is created in v0.8.1-I.",
    "No JSON object is created in v0.8.1-I.",
    "Fixture JSON artifact creation requires separate Owner authorization.",
    # creation authorization relationship
    "Creation authorization relationship is planning only.",
    "The artifact creation plan builds on the v0.8.1-H creation authorization plan.",
    "The artifact creation plan does not replace the creation authorization plan.",
    "The artifact creation plan does not modify the creation authorization plan.",
    "No creation authorization runtime is implemented in v0.8.1-I.",
    # explicit Owner authorization phrase relationship
    "Explicit Owner authorization phrase relationship is planning only.",
    "The future explicit Owner authorization phrase from v0.8.1-H must be separately issued before any artifact is created.",
    "The explicit Owner authorization phrase is not issued in v0.8.1-I.",
    "The explicit Owner authorization phrase is not satisfied in v0.8.1-I.",
    "No fixture JSON may be created from v0.8.1-I.",
    # candidate artifact path
    "Candidate fixture JSON path: fixtures/local_mock_data/hermes_openclaw_local_mock_messages_v0_8_1.json",
    "Candidate fixture JSON path is planning only.",
    "Candidate fixture JSON path is not created in v0.8.1-I.",
    "Candidate fixture directory is not created in v0.8.1-I.",
    "Candidate fixture JSON file is not created in v0.8.1-I.",
    "Candidate artifact path is inherited from v0.8.1-H planning.",
    # candidate artifact filename
    "Candidate fixture JSON filename: hermes_openclaw_local_mock_messages_v0_8_1.json",
    "Candidate fixture JSON filename is planning only.",
    "Candidate fixture JSON filename is not created in v0.8.1-I.",
    # candidate schema version
    "Candidate fixture JSON schema_version: v0.8.1-local-mock-1.",
    "Candidate schema version is planning only.",
    "Candidate schema version is not implemented in v0.8.1-I.",
    "No schema migration is performed in v0.8.1-I.",
    # candidate top-level shape blueprint
    "Candidate top-level shape blueprint is planning only.",
    "Candidate top-level shape may include schema_version.",
    "Candidate top-level shape may include fixture_id.",
    "Candidate top-level shape may include is_mock.",
    "Candidate top-level shape may include created_for.",
    "Candidate top-level shape may include records.",
    "Candidate top-level shape is expressed as plain text only.",
    "No JSON object is created in v0.8.1-I.",
    # candidate records collection blueprint
    "Candidate records collection blueprint is planning only.",
    "Candidate records collection may include six synthetic local-only records.",
    "Candidate records collection must not include real queue data.",
    "Candidate records collection must not include real user data.",
    "Candidate records collection must not include secrets.",
    "Candidate records collection must not include endpoints.",
    "No records collection is created in v0.8.1-I.",
    # candidate record count blueprint
    "Candidate record count blueprint: six records.",
    "Candidate record count is planning only.",
    "Candidate record count must remain small and reviewable.",
    "Candidate record count must not be generated from real queue data.",
    "No record is created in v0.8.1-I.",
    # candidate record ordering blueprint
    "Candidate record ordering blueprint: Mock Task Message first.",
    "Candidate record ordering blueprint: Mock Decision Message second.",
    "Candidate record ordering blueprint: Mock Result Message third.",
    "Candidate record ordering blueprint: Mock Advice Message fourth.",
    "Candidate record ordering blueprint: Mock Badge Status fifth.",
    "Candidate record ordering blueprint: Mock Runtime-off Status sixth.",
    "Candidate record ordering is planning only.",
    "Candidate record ordering must be deterministic.",
    # synthetic local-only value policy
    "Synthetic local-only value policy: all candidate values must be synthetic.",
    "Synthetic local-only value policy: all candidate values must be local-only.",
    "Synthetic local-only value policy: no value may be copied from real queue DB.",
    "Synthetic local-only value policy: no value may be copied from Google Sheets.",
    "Synthetic local-only value policy: no value may be copied from secrets.",
    "Synthetic local-only value policy: no value may be copied from production logs.",
    "Synthetic local-only value policy: no value may be copied from private user data.",
    "No real data is used in v0.8.1-I.",
    # no-real-data policy
    "No-real-data policy is planning only.",
    "No-real-data policy: the future artifact must contain no real queue IDs.",
    "No-real-data policy: the future artifact must contain no real task IDs.",
    "No-real-data policy: the future artifact must contain no real user data.",
    "No-real-data policy: the future artifact must contain no spreadsheet IDs.",
    "No-real-data policy: the future artifact must contain no tokens.",
    "No-real-data policy: the future artifact must contain no secrets.",
    "No-real-data policy: the future artifact must contain no endpoints.",
    # required fields blueprint
    "Required fields blueprint is planning only.",
    "fixture_id",
    "schema_version",
    "is_mock",
    "message_family",
    "message_id",
    "preview_id",
    "created_for",
    "display_title",
    "display_summary",
    "safety_notes",
    "next_owner_action",
    "audit_notes",
    "rollback_notes",
    "No required field is implemented in v0.8.1-I.",
    # forbidden fields rejection blueprint
    "Forbidden fields rejection blueprint is planning only.",
    "real_queue_id",
    "real_task_id",
    "real_user_secret",
    "spreadsheet_id",
    "refresh_token",
    "client_secret",
    "private_key",
    "webhook_url",
    "openclaw_endpoint",
    "hermes_endpoint",
    "production_db_url",
    "remote_blackboard_api_url",
    "No forbidden field value is included in v0.8.1-I.",
    # boolean safety invariant blueprint
    "is_mock = true",
    "dispatch_enabled = false",
    "worker_running = false",
    "openclaw_connected = false",
    "hermes_connected = false",
    "google_sheets_enabled = false",
    "external_side_effects = false",
    "approval_is_execution = false",
    "approval_readiness_is_execution = false",
    "artifact_creation_permission = false",
    "loader_permission = false",
    "dashboard_change_permission = false",
    "execution_permission = false",
    "dispatch_permission = false",
    "external_side_effects_permission = false",
    "No boolean safety invariant runtime is implemented in v0.8.1-I.",
    # message families
    "Mock Task Message",
    "Mock Decision Message",
    "Mock Result Message",
    "Mock Advice Message",
    "Mock Badge Status",
    "Mock Runtime-off Status",
    # per-family record blueprints
    "Mock Task Message record blueprint is planning only.",
    "Mock Task Message display_title candidate: Review mock queued task.",
    "Mock Task Message display_summary candidate: Synthetic queued task for Owner preview.",
    "Mock Task Message safety_notes candidate: Dispatch remains off and no Worker is started.",
    "Mock Task Message next_owner_action candidate: Review only; do not execute.",
    "No Mock Task Message record is created in v0.8.1-I.",
    "Mock Decision Message record blueprint is planning only.",
    "Mock Decision Message display_title candidate: Review mock owner decision.",
    "Mock Decision Message display_summary candidate: Synthetic Owner decision for audit preview.",
    "Mock Decision Message safety_notes candidate: Approval is not execution.",
    "Mock Decision Message next_owner_action candidate: Review only; dispatch remains separate.",
    "No Mock Decision Message record is created in v0.8.1-I.",
    "Mock Result Message record blueprint is planning only.",
    "Mock Result Message display_title candidate: Review mock worker result.",
    "Mock Result Message display_summary candidate: Synthetic result message for dry-run preview.",
    "Mock Result Message safety_notes candidate: Worker remains off and no OpenClaw call is made.",
    "Mock Result Message next_owner_action candidate: Review result display only.",
    "No Mock Result Message record is created in v0.8.1-I.",
    "Mock Advice Message record blueprint is planning only.",
    "Mock Advice Message display_title candidate: Review mock Hermes advice.",
    "Mock Advice Message display_summary candidate: Synthetic Hermes advice for readback preview.",
    "Mock Advice Message safety_notes candidate: Hermes remains not connected and no memory runtime is created.",
    "Mock Advice Message next_owner_action candidate: Review advice display only.",
    "No Mock Advice Message record is created in v0.8.1-I.",
    "Mock Badge Status record blueprint is planning only.",
    "Mock Badge Status display_title candidate: Review mock runtime safety badges.",
    "Mock Badge Status display_summary candidate: Synthetic safety badge status for Dashboard preview.",
    "Mock Badge Status safety_notes candidate: DISPATCH OFF, WORKER OFF, OPENCLAW NOT CONNECTED, HERMES NOT CONNECTED, GOOGLE SHEETS DISABLED.",
    "Mock Badge Status next_owner_action candidate: Confirm badges remain display-only.",
    "No Mock Badge Status record is created in v0.8.1-I.",
    "Mock Runtime-off Status record blueprint is planning only.",
    "Mock Runtime-off Status display_title candidate: Review mock runtime-off posture.",
    "Mock Runtime-off Status display_summary candidate: Synthetic runtime-off state for Owner review.",
    "Mock Runtime-off Status safety_notes candidate: No Worker, OpenClaw, Hermes, Google Sheets, POST, or real queue DB.",
    "Mock Runtime-off Status next_owner_action candidate: Confirm runtime remains off.",
    "No Mock Runtime-off Status record is created in v0.8.1-I.",
    # artifact creation checklist
    "Artifact creation checklist: explicit Owner authorization phrase must be separately issued before creation.",
    "Artifact creation checklist: candidate artifact path is reviewed.",
    "Artifact creation checklist: candidate filename is reviewed.",
    "Artifact creation checklist: candidate schema_version is reviewed.",
    "Artifact creation checklist: candidate top-level shape is reviewed.",
    "Artifact creation checklist: candidate records collection is reviewed.",
    "Artifact creation checklist: candidate record count is reviewed.",
    "Artifact creation checklist: candidate record ordering is reviewed.",
    "Artifact creation checklist: synthetic local-only policy is reviewed.",
    "Artifact creation checklist: no-real-data policy is reviewed.",
    "Artifact creation checklist: required fields are reviewed.",
    "Artifact creation checklist: forbidden fields are reviewed.",
    "Artifact creation checklist: boolean safety invariants are reviewed.",
    "Artifact creation checklist: message families are reviewed.",
    "Artifact creation checklist: no loader is authorized.",
    "Artifact creation checklist: no Dashboard change is authorized.",
    "Artifact creation checklist: no real queue DB read is required.",
    "Artifact creation checklist: no POST is required.",
    "Artifact creation checklist: no Worker/OpenClaw/Hermes action is required.",
    "Artifact creation checklist: no Google Sheets access is required.",
    "Artifact creation checklist: no secrets access is required.",
    # artifact rejection checklist
    "Artifact rejection checklist: reject artifact creation if explicit Owner authorization phrase is missing.",
    "Artifact rejection checklist: reject artifact creation if candidate artifact path is unclear.",
    "Artifact rejection checklist: reject artifact creation if candidate filename is unclear.",
    "Artifact rejection checklist: reject artifact creation if schema_version is unclear.",
    "Artifact rejection checklist: reject artifact creation if top-level shape is unclear.",
    "Artifact rejection checklist: reject artifact creation if records collection is unclear.",
    "Artifact rejection checklist: reject artifact creation if record count is unclear.",
    "Artifact rejection checklist: reject artifact creation if record ordering is unclear.",
    "Artifact rejection checklist: reject artifact creation if synthetic local-only confirmation is missing.",
    "Artifact rejection checklist: reject artifact creation if no-real-data confirmation is missing.",
    "Artifact rejection checklist: reject artifact creation if required fields are incomplete.",
    "Artifact rejection checklist: reject artifact creation if forbidden fields are present.",
    "Artifact rejection checklist: reject artifact creation if boolean safety invariants are unsafe.",
    "Artifact rejection checklist: reject artifact creation if loader permission is requested.",
    "Artifact rejection checklist: reject artifact creation if Dashboard change permission is requested.",
    "Artifact rejection checklist: reject artifact creation if execution permission is requested.",
    "Artifact rejection checklist: reject artifact creation if dispatch permission is requested.",
    "Artifact rejection checklist: reject artifact creation if external side effects are requested.",
    "Artifact rejection checklist: reject artifact creation if real queue DB read is required.",
    "Artifact rejection checklist: reject artifact creation if POST is required.",
    "Artifact rejection checklist: reject artifact creation if Worker/OpenClaw/Hermes action is required.",
    "Artifact rejection checklist: reject artifact creation if Google Sheets access is required.",
    "Artifact rejection checklist: reject artifact creation if secrets access is required.",
    # validation checklist
    "Validation checklist: artifact creation plan must remain synthetic local-only.",
    "Validation checklist: artifact creation plan must contain no fixture JSON.",
    "Validation checklist: artifact creation plan must contain no JSON object.",
    "Validation checklist: artifact creation plan must contain no mock data file.",
    "Validation checklist: artifact creation plan must contain no fixture directory.",
    "Validation checklist: artifact creation plan must contain no preview data loader.",
    "Validation checklist: artifact creation plan must contain no runtime.",
    "Validation checklist: artifact creation plan must contain no forbidden field values.",
    "Validation checklist: artifact creation plan must satisfy boolean safety invariants.",
    "Validation checklist: artifact creation plan must keep artifact_creation_permission = false.",
    "Validation checklist: artifact creation plan must keep loader_permission = false.",
    "Validation checklist: artifact creation plan must keep dashboard_change_permission = false.",
    "Validation checklist: artifact creation plan must not enable dispatch.",
    "Validation checklist: artifact creation plan must not enable Worker.",
    "Validation checklist: artifact creation plan must not connect OpenClaw.",
    "Validation checklist: artifact creation plan must not activate Hermes.",
    "Validation checklist: artifact creation plan must not enable Google Sheets.",
    "Validation checklist: artifact creation plan must not read real queue DB.",
    "Validation checklist: artifact creation plan must not send POST.",
    "Validation checklist: artifact creation plan must not read secrets.",
    # artifact rollback checklist
    "Artifact rollback checklist: future created artifact must be removable by deleting only the approved local fixture JSON file.",
    "Artifact rollback checklist: rollback must not require database migration.",
    "Artifact rollback checklist: rollback must not require real queue DB write.",
    "Artifact rollback checklist: rollback must not require POST.",
    "Artifact rollback checklist: rollback must not require Worker/OpenClaw/Hermes action.",
    "Artifact rollback checklist: rollback must not require Google Sheets access.",
    "Artifact rollback checklist: rollback must not require secrets access.",
    "Artifact rollback checklist: rollback must preserve Dashboard route/template/static unchanged unless separately approved.",
    # forbidden field rejection checklist
    "Forbidden field rejection checklist: reject if real_queue_id appears as a field.",
    "Forbidden field rejection checklist: reject if real_task_id appears as a field.",
    "Forbidden field rejection checklist: reject if real_user_secret appears as a field.",
    "Forbidden field rejection checklist: reject if spreadsheet_id appears as a field.",
    "Forbidden field rejection checklist: reject if refresh_token appears as a field.",
    "Forbidden field rejection checklist: reject if client_secret appears as a field.",
    "Forbidden field rejection checklist: reject if private_key appears as a field.",
    "Forbidden field rejection checklist: reject if webhook_url appears as a field.",
    "Forbidden field rejection checklist: reject if openclaw_endpoint appears as a field.",
    "Forbidden field rejection checklist: reject if hermes_endpoint appears as a field.",
    "Forbidden field rejection checklist: reject if production_db_url appears as a field.",
    "Forbidden field rejection checklist: reject if remote_blackboard_api_url appears as a field.",
    # boolean safety invariant checklist
    "Boolean safety invariant checklist is planning only.",
    "Boolean safety invariant checklist: is_mock = true.",
    "Boolean safety invariant checklist: artifact_creation_permission = false.",
    "Boolean safety invariant checklist: loader_permission = false.",
    "Boolean safety invariant checklist: dashboard_change_permission = false.",
    "Boolean safety invariant checklist: execution_permission = false.",
    "Boolean safety invariant checklist: dispatch_permission = false.",
    "Boolean safety invariant checklist: external_side_effects_permission = false.",
    # message family creation checklist
    "Message family creation checklist is planning only.",
    "Message family creation checklist: Mock Task Message record blueprint is reviewed.",
    "Message family creation checklist: Mock Decision Message record blueprint is reviewed.",
    "Message family creation checklist: Mock Result Message record blueprint is reviewed.",
    "Message family creation checklist: Mock Advice Message record blueprint is reviewed.",
    "Message family creation checklist: Mock Badge Status record blueprint is reviewed.",
    "Message family creation checklist: Mock Runtime-off Status record blueprint is reviewed.",
    "No message family record is created in v0.8.1-I.",
    # future artifact creation command boundary
    "Future artifact creation command boundary is planning only.",
    "The future artifact creation command must be separately Owner-authorized.",
    "The future artifact creation command must create only the synthetic local-only fixture JSON file.",
    "The future artifact creation command must not create a loader.",
    "The future artifact creation command must not modify Dashboard route/template/static.",
    "The future artifact creation command must not read real queue DB.",
    "The future artifact creation command must not send POST.",
    "The future artifact creation command must not start Worker.",
    "The future artifact creation command must not call OpenClaw.",
    "The future artifact creation command must not activate Hermes.",
    "The future artifact creation command must not read or write Google Sheets.",
    "No artifact creation command runtime is implemented in v0.8.1-I.",
    # future artifact validation boundary
    "Future artifact validation boundary is planning only.",
    "The future artifact must validate as synthetic local-only before any use.",
    "The future artifact must contain only approved message families.",
    "The future artifact must contain only approved required fields.",
    "The future artifact must contain no forbidden fields.",
    "The future artifact must satisfy boolean safety invariants.",
    "No artifact validation runtime is implemented in v0.8.1-I.",
    # future artifact rollback boundary
    "Future artifact rollback boundary is planning only.",
    "The future artifact must be removable by deleting only the approved local fixture JSON file.",
    "The future artifact rollback must not require database migration.",
    "The future artifact rollback must not require real queue DB write.",
    "The future artifact rollback must not require POST.",
    "No artifact rollback runtime is implemented in v0.8.1-I.",
    # future read-only loader boundary
    "A future read-only loader may read the approved fixture once it exists.",
    "Future read-only loader is display-only.",
    "Future read-only loader is not execution permission.",
    "Future read-only loader must not write the fixture.",
    "Future read-only loader must not read real queue DB.",
    "Future read-only loader must not send POST.",
    "No read-only loader runtime is implemented in v0.8.1-I.",
    "No preview data loader is implemented in v0.8.1-I.",
    # future Dashboard preview boundary
    "Dashboard may eventually display the approved local mock data fixture once created.",
    "Future Dashboard preview is display-only.",
    "No Dashboard fixture preview runtime is implemented in v0.8.1-I.",
    # Dashboard route / template / static boundary
    "Dashboard route boundary is planning only.",
    "No Dashboard route is created in v0.8.1-I.",
    "No Dashboard endpoint is created in v0.8.1-I.",
    "No Dashboard template is created in v0.8.1-I.",
    "No Dashboard static asset is created in v0.8.1-I.",
    "No app route is modified in v0.8.1-I.",
    "No template file is modified in v0.8.1-I.",
    "No static file is modified in v0.8.1-I.",
    # app / runtime boundary
    "App / runtime boundary is planning only.",
    "No app module is modified in v0.8.1-I.",
    "No app.main import is performed in v0.8.1-I.",
    "No QueueStore import is performed in v0.8.1-I.",
    "No runtime host is created in v0.8.1-I.",
    "No daemon is created in v0.8.1-I.",
    "No systemd service is created in v0.8.1-I.",
    "No Docker deployment is created in v0.8.1-I.",
    "No fixture loader runtime is created in v0.8.1-I.",
    # queue and real data boundary
    "No source-of-truth switch is performed.",
    "No queue DB change.",
    "No local queue data change.",
    "No Replit queue data change.",
    "No real queue DB read.",
    "No queue migration is performed.",
    "No queue synchronization is performed.",
    "No queue backfill is performed.",
    "No queue merge is performed.",
    "No conflict resolver is implemented.",
    "No shared write is enabled.",
    # Remote Blackboard API relationship
    "Remote Blackboard API remains planning only.",
    "Remote Blackboard API runtime is not implemented in v0.8.1-I.",
    "Remote Blackboard API read is not enabled in v0.8.1-I.",
    "Remote Blackboard API write is not enabled in v0.8.1-I.",
    "Remote Blackboard API is not required for artifact creation planning.",
    # separation
    "Worker remains OFF.",
    "OpenClaw remains Not Connected.",
    "Hermes remains Not Connected.",
    "Worker is dispatch runtime.",
    "OpenClaw is execution / gateway / tools layer.",
    "Hermes is strategy / proxy / memory layer.",
    "Worker must not run from plan-only artifact creation planning.",
    "OpenClaw must not execute from plan-only artifact creation planning.",
    "Hermes must not act from plan-only artifact creation planning.",
    # Google Sheets boundary
    "Google Sheets remains Disabled.",
    "No Google Sheets read is required.",
    "No Google Sheets write is performed.",
    "No Google Sheets live write is enabled.",
    # secrets / privacy / memory boundary
    "No secrets are read.",
    "No secrets are copied.",
    "No secrets are created.",
    "No .env file is created.",
    "No credentials are moved.",
    "No production secrets are copied.",
    "No Hermes memory store is created.",
    "No Hermes learning runtime is created.",
    "No private conversation log is created.",
    "No all-conversation logging is enabled.",
    # network / webhook / connector boundary
    "No webhook is created.",
    "No webhook receiver is created.",
    "No connector is created.",
    "No external network call is added.",
    "No inbound listener is added.",
    "No outbound integration is added.",
    "No port exposure is configured.",
    "No POST is sent.",
    "No live queue write validation is performed.",
    # disabled runtime list
    "Artifact creation planning runtime is disabled.",
    "Artifact creation command runtime is disabled.",
    "Fixture JSON creation authorization planning runtime is disabled.",
    "Fixture loader runtime is disabled.",
    "Preview data loader runtime is disabled.",
    "Local mock data preview runtime is disabled.",
    "Dashboard fixture preview runtime is disabled.",
    "Blackboard Loop runtime is disabled.",
    "Dashboard badge display runtime is disabled.",
    "Decision audit display runtime is disabled.",
    "Owner review checklist runtime is disabled.",
    "Dashboard preview display runtime is disabled.",
    "Dispatch gate is disabled.",
    "Worker runtime is disabled.",
    "OpenClaw runtime is disabled.",
    "Hermes runtime is disabled.",
    "Remote Blackboard API runtime is disabled.",
    "Shared write is disabled.",
    "Google Sheets write is disabled.",
    "Autonomous execution is disabled.",
    # current safe posture
    "Dashboard read-only / controlled local route behavior.",
    "Worker OFF.",
    "OpenClaw Not Connected.",
    "Hermes Not Connected.",
    "Google Sheets Disabled.",
    "DISPATCH OFF.",
    "WORKER OFF.",
    "OPENCLAW NOT CONNECTED.",
    "HERMES NOT CONNECTED.",
    "GOOGLE SHEETS DISABLED.",
    "No fixture JSON.",
    "No .json artifact.",
    "No mock data file.",
    "No seed data file.",
    "No fixture directory.",
    "No fixture loader runtime.",
    "No preview data loader.",
    "No local mock data preview runtime.",
    "No Artifact creation command runtime.",
    "No Blackboard Loop runtime.",
    "No Dashboard badge display runtime.",
    "No Decision audit display runtime.",
    "No Owner review checklist runtime.",
    "No Dashboard preview display runtime.",
    "No local dry-run preview runtime.",
    "No preview renderer runtime.",
    "No loop contract runtime.",
    "No state machine runtime.",
    "No loop scheduler.",
    "No dispatch gate enabled.",
    "No autonomous execution.",
    "No Hermes activation.",
    "No Hermes blackboard mode.",
    "No Hermes runtime.",
    "No Hermes memory store.",
    "No all-conversation logging.",
    "No cleanup demo task.",
    "No cleanup apply.",
    "No --apply.",
    "No task deletion.",
    "No task archive.",
    "No queue DB change.",
    "No local queue data change.",
    "No Replit queue data change.",
    "No real queue DB read.",
    "No POST.",
    "No live local queue write validation.",
    "No Worker execution.",
    "No OpenClaw call.",
    "No Hermes call.",
    "No Google Sheets read.",
    "No Google Sheets write.",
    "No secrets read.",
    "No secrets copied.",
    "No .env created.",
    "No webhook.",
    "No connector.",
    "No external side effects.",
    "No production DB.",
    "No shared DB.",
    "No remote shared DB.",
    "No Remote Blackboard API runtime.",
    "No Dashboard route created.",
    "No Dashboard endpoint created.",
    "No Dashboard template created.",
    "No Dashboard static asset created.",
    "No app route modified.",
    "No template file modified.",
    "No static file modified.",
    "No Core runtime host.",
    "No Worker runtime.",
    "No OpenClaw runtime.",
    "No systemd service.",
    "No daemon.",
    "No Docker deployment.",
    "No queue synchronization.",
    "No queue migration.",
    "No queue backfill.",
    "No queue merge.",
    "No conflict resolver.",
    "No fixture JSON created.",
    "No mock data file created.",
    "No seed data file created.",
    "No fixture directory created.",
    "No tag.",
    # validation summary
    "v0.8.1-I readiness: ALL PASS.",
    "v0.8.1-H readiness: ALL PASS.",
    "v0.8.1-G readiness: ALL PASS.",
    "v0.8.1-F readiness: ALL PASS.",
    "v0.8.1-E readiness: ALL PASS.",
    "v0.8.1-D readiness: ALL PASS.",
    "v0.8.1-C readiness: ALL PASS.",
    "v0.8.1-B readiness: ALL PASS.",
    "v0.8.1-A readiness: ALL PASS.",
    "v0.8.0-G readiness: ALL PASS.",
    "v0.8.0-F readiness: ALL PASS.",
    "v0.8.0-A readiness: ALL PASS.",
    "v0.7.5-A readiness: ALL PASS.",
    "compileall scripts: PASS.",
    # safety grep summary
    "No real unsafe claim was found.",
    "No real secret was found.",
    "Forbidden field names are allowed planning tokens.",
    "Readiness forbidden-pattern matches are benign.",
    # next recommended step
    "v0.8.1-J — Local Mock Data Fixture JSON Artifact Creation Authorization Review",
    "v0.8.1-J must not start unless separately approved by Owner.",
    "v0.8.1-J must not create fixture JSON unless separately approved by Owner.",
    "v0.8.1-J must not create preview data loader.",
    "v0.8.1-J must not modify Dashboard route/template/static.",
    "v0.8.1-J must not read real queue DB.",
    "v0.8.1-J must not send POST.",
    "v0.8.1-J must not start Worker.",
    "v0.8.1-J must not call OpenClaw.",
    "v0.8.1-J must not activate Hermes.",
    "v0.8.1-J must not read or write Google Sheets.",
]
for token in REQUIRED:
    ok(f"doc 含「{token}」") if token in doc else xx(f"doc 含「{token}」")

# ---------------------------------------------------------------------------
# [4] 禁止包含的不安全聲明 / 機密
#     先移除合法的安全否定句（其字面含 forbidden 子字串），再掃 forbidden。
#     forbidden field 名稱（bare token）為 allowed planning token，僅以 value-form
#     pattern 偵測真實機密，故不會誤判。
# ---------------------------------------------------------------------------
print("[4] 禁止包含的不安全聲明 / 機密")
SAFE_NEGATIONS = [
    "No secrets read.",
    "No secrets copied.",
    "No .env created.",
    "No dispatch gate enabled.",
    "Artifact creation checklist: no real queue DB read is required.",
    "Artifact rejection checklist: reject artifact creation if real queue DB read is required.",
    "real queue DB read is required.",
    "No real queue DB read.",
    "No fixture JSON created.",
    "No mock data file created.",
    "No seed data file created.",
    "No fixture directory created.",
    "No Google Sheets read is required.",
    "No Google Sheets read.",
    "No Dashboard route created.",
    "No Dashboard endpoint created.",
    "No Dashboard template created.",
    "No Dashboard static asset created.",
    "No app route modified.",
    "No template file modified.",
    "No static file modified.",
]
scrubbed = doc
for phrase in SAFE_NEGATIONS:
    scrubbed = scrubbed.replace(phrase, "")

FORBIDDEN_SUBSTR = [
    "GOOGLE_SHEETS_ENABLED=true",
    "fixture JSON created",
    "fixture directory created",
    "mock data file created",
    "seed data file created",
    "fixture loader runtime created",
    "fixture loader runtime implemented",
    "preview data loader created",
    "preview data loader implemented",
    "local mock data preview runtime created",
    "local mock data preview runtime implemented",
    "Dashboard fixture preview runtime created",
    "Dashboard fixture preview runtime implemented",
    "Artifact creation command runtime created",
    "Artifact creation planning runtime created",
    "Authorization request runtime created",
    "Authorization decision runtime created",
    "Owner approval request runtime created",
    "Owner approval decision runtime created",
    "Blackboard Loop runtime created",
    "Blackboard Loop runtime implemented",
    "Blackboard Loop runtime enabled",
    "Dashboard badge display runtime created",
    "Dashboard preview display runtime created",
    "Dashboard preview display runtime implemented",
    "Dashboard preview display runtime enabled",
    "preview renderer runtime created",
    "Dashboard route created",
    "Dashboard endpoint created",
    "Dashboard template created",
    "Dashboard static asset created",
    "app route modified",
    "template file modified",
    "static file modified",
    "loop contract runtime created",
    "state machine runtime created",
    "loop scheduler created",
    "loop scheduler enabled",
    "dispatch gate enabled",
    "autonomous execution enabled",
    "Worker enabled",
    "Worker started",
    "Worker runtime created",
    "Worker dispatch enabled",
    "OpenClaw connected",
    "OpenClaw called",
    "OpenClaw runtime created",
    "Hermes connected",
    "Hermes activated",
    "Hermes called",
    "Hermes runtime created",
    "Hermes memory store created",
    "Hermes learning runtime created",
    "Hermes blackboard mode enabled",
    "Google Sheets live write enabled",
    "Google Sheets read",
    "Google Sheets written",
    "Remote Blackboard API runtime created",
    "Remote Blackboard API implemented",
    "Remote Blackboard API read enabled",
    "Remote Blackboard API write enabled",
    "production DB created",
    "shared DB created",
    "remote shared DB created",
    "queue DB read",
    "real queue DB read",
    "queue DB modified",
    "local queue data modified",
    "Replit queue data modified",
    "queue migration performed",
    "queue data synchronized",
    "queue data moved",
    "queue data copied",
    "queue data merged",
    "queue data backfilled",
    "conflict resolver implemented",
    "shared write enabled",
    "Blackboard shared write enabled",
    "POST to Replit Preview was sent",
    "POST to real queue was sent",
    "live queue write validation performed",
    "webhook created",
    "webhook receiver created",
    "connector created",
    "external network call added",
    "API route added",
    "FastAPI router added",
    "database client added",
    "migration added",
    "schema migration performed",
    "source-of-truth switch performed",
    "cleanup applied",
    "demo task cleaned up",
    "tasks deleted",
    "tasks archived",
    "apply_allowed = True",
    "apply_requested = True",
    "dry_run = False",
    "external_side_effects = True",
    "approval_is_execution = True",
    "approval_readiness_is_execution = True",
    "dispatch_enabled = True",
    "artifact_creation_permission = True",
    "loader_permission = True",
    "dashboard_change_permission = True",
    "execution_permission = True",
    "dispatch_permission = True",
    "external_side_effects_permission = True",
    "secrets read",
    "secrets copied",
    "secrets created",
    ".env created",
    "credentials moved",
    "tag created",
]
for token in FORBIDDEN_SUBSTR:
    ok(f"doc 無「{token}」") if token not in scrubbed else xx(f"doc 不得含「{token}」")

# value-bearing secret patterns only (bare forbidden-field tokens are allowed planning tokens)
FORBIDDEN_PATTERNS = [
    (r"spreadsheets/d/[A-Za-z0-9_-]{20,}", "real spreadsheet URL"),
    (r'"?refresh_token"?\s*[:=]\s*"[^"]+"', "refresh token value"),
    (r'"?client_secret"?\s*[:=]\s*"[^"]+"', "client secret value"),
    (r'"?private_key"?\s*[:=]\s*"[^"]+"', "private key value"),
    (r"-----BEGIN[ A-Z]*PRIVATE KEY-----", "private key block"),
    (r'"?spreadsheet_id"?\s*[:=]\s*"[A-Za-z0-9_-]{20,}"', "spreadsheet id value"),
    (r"dashboard_token\s*=\s*[A-Za-z0-9_\-]{8,}", "dashboard token value"),
]
for pat, label in FORBIDDEN_PATTERNS:
    found = bool(re.search(pat, doc, re.IGNORECASE))
    ok(f"doc 無「{label}」") if not found else xx(f"doc 不得含「{label}」")

# ---------------------------------------------------------------------------
# 結果
# ---------------------------------------------------------------------------
total = len(PASS) + len(FAIL)
print(f"\n合計：{len(PASS)}/{total} 通過")
if FAIL:
    print(f"\nXX v0.8.1-I readiness 失敗 {len(FAIL)} 項：")
    for f in FAIL:
        print(f"   - {f}")
    sys.exit(1)
else:
    print(
        "\nv0.8.1-I Local Mock Data Fixture JSON Artifact Creation Plan readiness: ALL PASS"
    )
    sys.exit(0)
